### ISSUE TITLE
Optimize GH Actions

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#101]
**Subtasks**  
Add all related subtasks to be completed in order to finish the issue.
- [x] Rename 1.x branch to v1
- [x] Use branch name to deploy build artefacts in sub folders e.g. on ui.porsche.com/v1/
- [x] Deploy branches of v1 PR's and define format
- [x] Update GH Actions filter
- [x] Add more informative Slack Notification by GH Actions
- [x] Automatically check if deployment worked correctly
- [x] Deploy latest version in dir latest too
- [x] Redirect from ui.porsche.com to ui.porsche.com/latest
- [x] Disable index.html build in 0.x CircleCI pipeline
- [x] comment out verify deploy task and ask business support of GH why this does not work
