### ISSUE TITLE
Select options not in sync

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#1011]
**Description**  
Available options of select are not always in sync with a given filter value.

**To Reproduce**  
1. Using `p-select` with filter activated
1. Search for a non existing option until an empty list is shown
1. Click outside of select to close options
1. Click on select so that option list re-opens
1. An empty option list is shown although filter value is empty

**Expected behavior**  
The option list should not be empty but show all available options because the search filter ist also empty after re-opening the option list.

**Notes**
Porsche Finder team (Jan Wenger) reported this issue.

**Subtasks**
- [x] fix syncing of options
- [x] fix update of selected element (#1017)
- [x] change auto positioning to default and optimized it
