### ISSUE TITLE
Create Style / Spacings

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#11]
**Scope**  
Research on the right UI definition for spacings and finalizing all spacing related styles.

**Notes**  
- Switch to 8-px-grid
- Horizontal and vertical spacings for layouting should be in 8-px-steps, defined by using the available basic spacing classes
- Within components (i.e. line-height for typo or buttons) the spacing scale can be reduced to 4-px-steps, to enable more details. Except of the spacing-4 these spacings wont be offered as classes but using defined mixins/variables 

- **Basic Spacing Classes**
spacing-4 (= special size, exception for 8-pt-steps)
spacing-8
spacing-16
spacing-24
spacing-32
spacing-40
spacing-48
spacing-56
spacing-64
spacing-72
spacing-80

- **Responsive Spacings**

| Klasse | Viewport XS | Viewport S | Viewport M | Viewport L | Viewport XL |
|-----|---------------|---------------|---------------|---------------|---------------|
|  spacing-a | 4 | 8 | 12 | 16 | 20 |
|  spacing-b | 8 | 16 | 24 | 32 | 40 |
|  spacing-c | 16 | 24 | 32 | 40 | 48 |
|  spacing-d | 24 | 32 | 40 | 48 | 56 |
|  spacing-e | 32 | 40 | 48 | 56 | 64 |
|  spacing-f | 40 | 48 | 56 | 64 | 72 |
|  spacing-g | 48 | 56 | 64 | 72 | 80 |

**Subtasks**  
- [x] Create UI decision proposal based on research and testing
- [x] Definition of hierarchy structure and naming of all related states and variants in design and code
- [x] UI definition approved

**― Design**
- [x] Create UI/UX guidelines as .md and include corresponding guideline pictures

**― Development**
- [x] Add "spacing" prefix to compiled css classes
- [x] Add "reset-to-zero" property to react component breakpoint specific => **this is a new feature and should be addressed in a new story (see #124)**
- [x] Transfer 0.x react component with styles (CSS) and component (JS) to 1.x
- [x] Create UI/UX guidelines as .mdx
- [x] Create/update related code CSS / JS
- [x] Create samples of all possible states and variants
- [x] Create Code/Implementation guidelines as .mdx for corresponding component code
- [x] Create VRT
- [x] Test code visual and functional for optimized viewports (only one browser): 320px, 375px, 480px, 768px, 1024px, 1366px, 1920px
- [x] Test code visual and functional for all supported browsers in viewports: 320px, 480px, 760px, 1000px, 1300px, 1760px, 1920px
