### ISSUE TITLE
Provide compiled CSS

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#111]
**Scope**  
Create automated CSS compiling for each component and an overall package

**Notes**  
- Provide via NPM and CDN

**Subtasks**  
Add all related subtasks to be completed in order to finish the issue.
- [ ] Create CSS compiling automatisation
- [ ] Setup deployment to NPM
- [ ] Setup CDN releasing
