### ISSUE TITLE
Use rollup for icon/meta-icons/fonts/marque package builds instead of tsc

### ISSUE THREAD

**Issue by denyo** [porsche-design-system/porsche-design-system#1130]
Scope
---
To further unify the way of how packages are built and bundled we should adjust our old packages that are still using `tsc` and multiple `tsconfig.json`s to transpile the code by switching to `rollup`.

While doing so, rollup.configs should be extracted into shared package and reused.
Also `jest.config.js` for unit test setup should be moved into the shared package and reused.

Notes
---
- E.g. `Partials` & `Assets` package are bundled by rollup
- Fallback package is already using rollup but not completely (example)
- Different output formats may result in multiple configs
- Related: https://github.com/porsche-design-system/porsche-design-system/issues/2710

Acceptance criteria
---
- [ ] rollup.config is shared in `shared` package
- [ ] jest.config is shared in `shared` package
- [ ] tsc is replaced with rollup in assets package
- [ ] tsc is replaced with rollup in meta-icons package
- [ ] tsc is replaced with rollup in icons package
- [ ] tsc is replaced with rollup in fonts package
- [ ] tsc is replaced with rollup in marque package
- [ ] tsc is replaced with rollup in fallbacks package
- [ ] tsc is replaced with rollup in email package

Subtasks
---
- [ ] extract rollup config into shared place
- [ ] extract jest.config.js into shared place
- [ ] move `--coverage` cli flag into config https://jestjs.io/docs/configuration#collectcoverage-boolean
- [ ] check if spec files are transpiled by rollup and fix if so
