### ISSUE TITLE
Replace CircleCI CI/CD with GitHub Actions for v0 builds

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#117]
**Scope**  
To get rid of Circle CI in favor of GH Actions it's necessary to replace it.

**Subtasks**  
Add all related subtasks to be completed in order to finish the issue.
- [x] Rename branch to v0
- [x] Use existing GH Actions workflow and docker image and adapt tasks for v0 deployments
- [x] Whenever someone pushes to v0 branch ui-kit-core and ui-kit-react is build
- [x] Delete old 0.x versioned releases in gh-pages
- [x] Test if issue deployments for 0.x still works
