### ISSUE TITLE
Create Component / Button Regular

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#12]
**Scope**  
Research and reevaluate the current UI definition of buttons and finalize all related designs and develop  button component.

**Out of Scope**
- Icon and Loader Component

**Props** (if relevant)  
- Name: Button Regular
- States: default, hover, focus, active, disabled, loading
- Variants: filled (default) / ghost, small, stretch + different types (basic, highlight, sales)
- Cases/Templates: Single full width (mobile), 50:50 row group (mobile), row same height, stacked group below same width (mobile)
- Themes: standard + inverted

**Subtasks**  
- [x] Create UI decision proposal based on research and testing
- [x] Definition of hierarchy structure and naming of all related states and variants in design and code
- [x] UI definition approved
- [x] Create/update Sketch library symbol 
- [x] Sync Sketch library and guideline pictures to InVision Project
- [x] Create UI/UX guidelines as .md and include corresponding guideline pictures from Invision
- [x] Create/update related styles (CSS) and component (JS)
- [x] Create samples of all possible states and variants
- [x] Create Code/Implementation guidelines as .md for corresponding component code
- [x] Create VRT and Unit test
- [x] Test code visual and functional for optimized viewports (only one browser): 320px, 375px, 480px, 768px, 1024px, 1366px, 1920px
- [x] Test code visual and functional for all supported browsers in viewports: 320px, 480px, 760px, 1000px, 1300px, 1760px, 1920px
