### ISSUE TITLE
Provide Meta-icons as partial

### ISSUE THREAD

**Issue by denyo** [porsche-design-system/porsche-design-system#1201]
Scope
---
To make meta icons easier to integrate and update we want to provide the site manifest including the reference of the corresponding assets as partial to be included in the header section.

Acceptance criteria
---
- [x] Provide meta icons as partial and update docu
- [x] Include partial into UX platform, storefront and sample projects

Subtasks
---
- [x] use metaicons manifest for complete set of icons
- [x] add unit tests
- [x] add test to verify if partials is reexported in package (react/angular)
- [x] add configurable cdn path (check configs of other partials)
- [x] use replacement script in angular and vanilla-js
- [x] discuss manifest (android) icons as separate partial
- [x] generate manifest.webmanifest, provide reference in metaIcons partial
- [x] discuss colors (theme/msapplication tile color as separate partial / passed value
- [x] research: find out if a `manifest.json` is required for android icons or if it is possible to have the android icons in the `<head>` (it is required `manifest.webmanifest` https://css-tricks.com/how-to-favicon-in-2021/) 
- [x] ask @o-hook  if `theme-color` and `msapplication-TileColor` need to be `#FFFFFF` (reply: colors should stay hard-coded and will be made configurable upon request)
- [x] remove PWA plugin from storefront
- [x] verify smoketest
- [x] add cors headers for webmanifest
