### ISSUE TITLE
Create Component / Spinner

### ISSUE THREAD

**Issue by o-hook** [porsche-design-system/porsche-design-system#125]
**Scope**  
Transfer and refactor Spinner component from UI Kit React v0. Define predefined spinner sizes.

Abstract Collection Link:
https://share.goabstract.com/99b5aed1-0de5-4c57-9f96-bf2cc8adf0cc

Notion Link:
https://www.notion.so/porscheui/Spinner-6ba1a6e8c3dc4c06b370aa8012817a3b

**Subtasks**  
// DESIGN
- [x] (Design) Define max 4 predefined loader sizes (Design and Development) based on spacing/size system
- [x] Add missing Spinner sizes
- [x] Rename Loader to Spinner
- [x] Create branch in Abstract according to issue number, update sketch library and add collection link issue
- [x] Create must-have design docu including (optionally create and upload assets)
- [x] Remove elements from prep library (optional)

// DEV
- [x] Transfer and refactor Loader component from UI Kit React v0
- [x] Create/update related styles (CSS) and component (JS)
- [x] Create dev docu .mdx(s)
- [x] Create samples of all possible states and variants
- [x] Refactor to web component
- [x] Create and perform VRT test
- [x] Rename Loader component into Spinner
- [x] Test code visual and functional for all supported browsers in viewports: 320px, 480px, 760px, 1000px, 1300px, 1760px, 1920px

// QA
- [x] 3rd party design sketch review
- [x] 3rd party design docu review
- [x] 3rd party code review
- [x] 3rd party code docu review
- [x] Code docu review by design 
- [x] Merge corresponding Abstract branch to master 
- [x] Export sketch lib file for deployment
