### ISSUE TITLE
Optimize Flex Component

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#126]
**Scope**  
Following subtasks are meant to be optimizations for the existing flex v1 component.

**Subtask**  
- [x] `p-flex--inline` class is used without block element, which does not fit BEM architecture
- [x] get rid of Text component in code example and use default <p> tags to have no dependencies to other components
- [x] Shouldn't `flexItem` React component be renamed to `flexChild` to be in sync with CSS classes? **=> Should be vise versa: change CSS classes and docs to "flex item" which is the official descriptor for flex children.**
- [x] Evaluate if SCSS flex mixins are needed, maybe add a more useful mixin that is capable of generating breakpoint specific classnames.
