### ISSUE TITLE
Create Components / Data Table

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#1289]
Scope
---
We want to provide a standard solution for wrapping and display different kinds of data or other components (e.g. link) in an organized table. We want to provide a **data table web-component** in shadow-dom with all relevant partials (table, table-head, table-row, table-cell), similar to https://web-components.carbondesignsystem.com/?path=/docs/components-data-table--default

Initial scope features
---
* Visible/Invisible caption (can be rendered as headline within `caption` tag
* Sorting of entries via table header
* ~~Fixed table header~~ (not possible due to horizontal scrolling)
* Loading state (evaluate possible solution but implement only with consultation by @marcelbertram)
* Empty state (evaluate possible solution but implement only with consultation by @marcelbertram)
* ~~Link support for rows~~ (text selection wouldn't be possible)
* Default Alignment in cell left & middle
* ~~Colspan for a second expanded row~~ > new story
* Auto width for cells and possibility to define min-width & max-width
* No-wrap for placed links/buttons/etc.
* Horizontally scrollable table

Out of scope
---
* No further exploration of code example distribution
* No footer 

Notes  
---
- Evaluate multiple implementations static data model, data templates, etc.
- Provide implementation example for VanillaJS/React/Angular via Code Snippets in Storefront
- Shared Component Digital Sales to replace: https://uikit.slfinpub.aws.porsche.cloud/?path=/docs/other-table--default
- Data Table Resources: Angular/React Components + JSON: [Data-Table-Resources.zip](https://github.com/porscheui/porsche-design-system/files/6400182/Data-Table-Resources.zip)

Research
---
- Accessibility: https://inclusive-components.design/data-tables/
- Accessibility and sortable: https://adrianroselli.com/2021/04/sortable-table-columns.html 
- Preparation of Retail Portfolio: Audit and Priorisation
https://app.mural.co/t/porscheagaccount2326/m/porscheagaccount2326/1614007349022/57622af8b2278598653b6f2a5dde10db0838e11c
- Online Car Sales (password = porsche): [Inventory List](https://ya7z87.axshare.com/#id=90xm0i&p=inventory_list&g=1), [Marketplace list](https://ya7z87.axshare.com/#id=wvbl3x&p=marketplace_list&g=1), [Contracts List](https://ya7z87.axshare.com/#id=5o227a&p=contracts_list&g=1), [List of merchants ](https://ya7z87.axshare.com/#id=mdnm41&p=list_of_merchants&g=1), [Inventory My Porsche (password = mhpporsche)](https://gzj5ec.axshare.com/#g=1&p=my_stock), [Finder](https://app.abstract.com/projects/19b9b6c1-e009-438a-aca5-4c5c98478667/branches/8ac3e927-0442-4c9a-be8f-4139461e6ec0/commits/683df7760eb36c76675aaa6612d9a016bbe08896/files/1a2b3822-925b-47ca-a069-2229aa099d52/layers/A0174374-A06C-4BD8-80D5-EA93C72672A8) 
- [Motorsport](https://app.abstract.com/projects/a8e9fd1c-b06c-45d0-8960-3a8125f15aa1/branches/master/collections/7fa1b323-6d23-4634-b648-8c27ae406f69)
- Best Practices: [Lightning](https://www.lightningdesignsystem.com/components/data-tables/), [Carbon](https://www.carbondesignsystem.com/components/data-table/usage/), [Material](https://material.io/components/data-tables#theming), [Medium](https://medium.com/nextux/design-better-data-tables-4ecc99d23356)
- Research: https://www.notion.so/porscheui/Data-Table-9bd833a1c1844c828b1036acd50bd49d
- Abstract: https://share.goabstract.com/272cec61-4f60-4d1f-8db5-66242b201eb3 and https://share.goabstract.com/82b87ced-0a52-4528-b226-571064c3bcf5
- Usage Guideline (Darft): https://www.notion.so/porscheui/Usage-Guideline-Draft-bbff03cdf53e4f90b7c2c26e01a20b56

Acceptance criteria
---
- [x] Interview about the existing technical concept with sponsor team devs (Porsche C@P Team)
- [x] Decide on implementation strategy: web-component for complex data table, simple tbd
- [x] Provide data table component
- [ ] Provide interactive implementation example with filter and pagination

**Subtasks**  
- [x] Research
- [x] Draft Component
- [x] Discuss within Team (with at least one team member)
- [x] Write Usage guideline
- [x] Create Data table component
- [x] Support table caption
- [x] How to specify column width? (on both head and body cells? just on head cells for convenience?)
- [x] ~Collapsable column per row (see screenshot)~
- [x] Storefront example with links (currently only on local components playground)
- [x] E2E Tests (for changing table header data, sorting callback, aria attributes, scroll behavior)
- [x] VRT Tests
- [x] Missing unit tests

Open Questions
---
- [x] Link support per row: YES, should be the main CTA. But other interactive elements within the row should be independently clickable, e.g. context-menu. If possible mark&copy text should still work. Hover highlight (only background color) according to select. Provide as example
- [x] What about wrap vs no-wrap for p-link, p-link-pure, p-button and p-button-pure? > No-wrap, content defines min width
- [x] Focus, hover, disabled states for table cell > only hover. As row acts as link and not as a button. All native aria elements should be included to support keyboard navigation
- [x] Sublines, like C@P has? > Provide a "flexible space" to expand the row spaning the complete row to place any individually styled content or components
- [x] Shall table be scrollable horizontal only? > Yes only horizontally
- [x] Sticky header support? > Yes as prop TIMEBOX 30min

<img width="834" alt="Bildschirmfoto 2021-05-11 um 12 12 10" src="https://user-images.githubusercontent.com/30120450/117799456-68307280-b252-11eb-8d9b-8cbdcd5e8c45.png">

- [x] How to handle horizontal scrolling? Should scroll bar always be visible? Should it be styled for this special case?
- [x] How to handle live example documentation? Static examples with JS code block
- [x] Manual browser testing
- [x] min spacing between table and slotted caption
