### ISSUE TITLE
Create Component / Button Icon

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#13]
**Scope**  
Research and reevaluate the current UI definition of buttons and finalize all related designs and develop button component.

**Abstract Collection Link**
LIGHT: https://share.goabstract.com/18d6d3f0-5e34-4265-9bad-6599ab50b0c2
DARK: https://share.goabstract.com/b45ed9b8-cc46-4c98-a04f-f7288a5d4f81

**Docu**
- Notion Link: https://www.notion.so/porscheui/Button-Icon-781a83c09260456dae353cbf8bdb26ae

**@ DEV: Please note**
Components will be refactored in Sketch later due to new styles / spacings.
Please adapt as follows:
- Icon size changes to 24 x 24, spacing top/bottom/left/right changes accordingly to 12 px (resulting in a total button height of 48 px).
- Button will be usable with rectangle BG and without BG (= clickable icon only).
- Default icon: Arrow

**Out of Scope**
- Icon and Loader Component

**Props** (if relevant)    
- Name: Button Icon
- States: default, hover / active, disabled, focus, loading
- Variants: filled (rectangle), ghost (rectangle), without background (= icon only)
- Cases/Templates: row
- Themes: light + dark

**Subtasks**  
// DESIGN
- [x] Create UI decision proposal based on research and testing
- [x] Definition of hierarchy structure and naming of all related states and variants in design and code
- [x] UI definition approved
- [x] Sketch refactoring: Adaption of new layer/text styles, spacings and icons
- [x] Build Button Icon without background as Sketch component
- [x] Sketch structure: Check override options (integrate emojis, check wording etc.)
- [x] Check focus state: Adapt border in new focus color instead of hover state?
- [x] Create branch in Abstract according to issue number, update sketch library and add collection link issue
- [x] Create must-have design docu including (optionally create and upload assets)
- [x] Remove elements from prep library (optional)
- [x] Replace code examples in design docu by corresponding component

// DEV
- [x] Create web component
- [x] Create samples of all possible states and variants
- [x] Create Code/Implementation guidelines
- [x] Create and perform VRT
- [x] Test code visual and functional for optimized viewports (only one browser): 320px, 375px, 480px, 768px, 1024px, 1366px, 1920px
- [x] Test code visual and functional for all supported browsers in viewports: 320px, 480px, 760px, 1000px, 1300px, 1760px, 1920px

// QA
- [x] 3rd party design sketch review
- [x] 3rd party design docu review
- [x] 3rd party code review
- [x] 3rd party code docu review
- [x] Code docu review by design 
- [x] Merge corresponding Abstract branch to master 
- [x] Export sketch lib file for deployment
