### ISSUE TITLE
Create Component / Porsche Marque

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#131]
**Scope**  
Create component containing the Porsche marque in different sizes and variations (US / rest of the world)

**Notes**  
- Use the assets from Porsche CDN
- Respect the spacing requirements of marque margin
- Assets 2018-06-15_porsche-marque-rgb-digital_S-L_R.zip
- Brand Guide Docu Marque: [Porsche_Markenzeichen_Signets.pdf](https://github.com/porscheui/porsche-ui-kit/files/3508562/Porsche_Markenzeichen_Signets.pdf)
- Examples for responsive logos: http://responsivelogos.co.uk/

**Props**
- Name: Porsche Marque
- Variants: US (copyright), Rest of the World, Small and Large
- Themes: standard

**Abstract**
https://share.goabstract.com/05819617-eec0-494b-93c8-6a2106a471dd

**Notion**
https://www.notion.so/porscheui/Porsche-Marque-7e16f68413ce450594da0aa6ae048bcc

**Subtasks**  
// DESIGN
- [x] Clarify with brand management possibilities of responsive reduced crest / marque: seperate appointment with meta design
- [x] Define naming and hierarchy structure and naming of all related states and variants
- [x] Create branch in Abstract according to issue number, update sketch library and add collection link issue
- [x] Create must-have design docu including (optionally create and upload assets) based on essentials of Brand Guide docu
- [x] Remove elements from prep library (optional)

// DEV
- [x] Setup of hierarchy structure and naming of all related states and variants
- [x] Create/update related code CSS / JS
- [x] Create samples of all possible states and variants
- [x] Create code docs (implementation guidelines)
- [x] Create VRT
- [x] Test code visual and functional for optimized viewports (only one browser): 320px, 375px, 480px, 768px, 1024px, 1366px, 1920px
- [x] Test code visual and functional for all supported browsers in viewports: 320px, 480px, 760px, 1000px, 1300px, 1760px, 1920px

// QA
- [x] 3rd party design sketch review
- [x] 3rd party design docu review
- [x] 3rd party code review
- [x] 3rd party code docu review
- [x] Code docu review by design 
- [x] Merge corresponding Abstract branch to master and export sketch lib file for deployment
