### ISSUE TITLE
Update component subnavi in storefront

### ISSUE THREAD

**Issue by annakrohmer** [porsche-design-system/porsche-design-system#132]
**Scope**  
Currently the component subnavi (tab navigation) is built up as follows:
EXAMPLES - DESIGN - PROPS

![image](https://user-images.githubusercontent.com/43340739/57223858-c6913d80-7007-11e9-99f5-f9ea153e7039.png)

For a quick-win-solution we should change it to:
DESIGN - CODE (or DEVELOP?) - PROPS

Reasons:
- "Examples" is a bit misleading as it mainly contains coding specs. Therefore, "Code" or "Develop" would be better? (see Material Design: https://material.io/develop/web/components/buttons/ - seems to be quite smart to have a more activating wording like "Design" and "Develop"?)
- "Design" should appear first, as it contains basic documentation on when and how to use this component and is the first description to be used in the UI/UX workflow. 

Examples: 

![image](https://user-images.githubusercontent.com/43340739/57223877-d6108680-7007-11e9-9b5f-2b43d1800043.png)
https://www.carbondesignsystem.com/components/breadcrumb/code / 

![image](https://user-images.githubusercontent.com/43340739/57223885-dc066780-7007-11e9-90b1-481b43da8443.png)
https://material.io/develop/web/components/buttons/

**To be defined:**
Would it (perspectively) make sense to…
- … split "Design" in "Usage" and "Style" (separate UX from UI documentation)?
- … split "Examples" in "Code" and "Examples" (so that "Examples" contains the different states/views of a component and is therefore valuable for both design and development?)?
→ To be discussed!

**Subtasks**  
- [x] Change subnavi structure + namings in code
- [x] Push my commits to GitHub
- [x] Open a pull request
