### ISSUE TITLE
Spike: Web Components

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#133]
**Scope**  
Regarding integration of UI Kit components into different JavaScript frameworks like Angular, React and VueJS it's necessary to evaluate the usage of Web Components and a framework like Stencil JS to produce them.

**Subtasks**  
- [x] Get pro account
- [x] Make yourself familiar with documentation of StencilJS 
- [x] Stencil vs Polymer
- [x] Create Web Components with StencilJS
- [x] Test on-way data-binding of a compiled web component in different browsers 
- [x] Test events and states of a compiled web component in different browsers
- [x] Test CSS scoping and scoping of compiled web component in general
- [x] Check compiler options (single vs bundle builds)
- [x] Check size of web components (especially polyfilled version vs native one)
- [x] Check IE11 support and general browser support
- [x] Evaluate effort of reworking the current storefront + workshop with StencilJS
- [x] Setup demo project in Angular, React, VueJS and integrate some web components as example
- [x] Produce a npm package with some sample components (button + icon) and try to implement them in different product teams with different JS frameworks
- [x] Onboarding session with stencil for plugins (02.07.)
- [x] Test auto generating of framework specific components: build complete
