### ISSUE TITLE
Library and Layout Template / Update

### ISSUE THREAD

**Issue by annakrohmer** [porsche-design-system/porsche-design-system#134]
**Scope**  
After finishing the basic components, we have to update the Sketch library template accordingly:

- Adapt new text styles (bold headlines etc.) 
- Adapt new colors / layer styles (page backgrounds)
- Adapt new spacings (incl. 4 px grid)

**To be defined**
Shall we provide the library template (to enable teams to build project-specific libraries) within the UI Kit storefront?

**Subtasks**  
- [x] Update Sketch library template in Abstract
- [x] Push my commits to Abstract
- [x] 3rd party design sketch review
- [x] Upload Layout and Layout Template for download

// QA
- [x] 3rd party review
