### ISSUE TITLE
Create Component / Pagination

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#138]
**Scope**  
Refactor Pagination component.

**Abstract Link**
https://share.goabstract.com/87d7e080-33d1-45a4-80fd-0b83296cebb7

**Notes**
- responsive behaviour: set prop by viewport with pageRange = auto between 1 = desktop, 0 = mobile

**Props** 
- Name: Pagination
- States: default, hover, active, disabled, focus
- Variants: different text sizes, see above
- Themes: light + dark

**Subtasks**  
// DESIGN
- [x] Sketch refactoring: Adaption of new layer/text styles, spacings and icons, new focus color, change status "current" to "active"
- [x] Sketch structure: Check override options (integrate emojis, check wording etc.)
- [x] Create/update Sketch library symbol in Abstract Branch and share collection link
- [x] Create must-have design docu (optionally create and upload assets)
- [x] Remove elements from prep library (optional)

// DEV
- [x] Adapt new focus color 
- [x] Create/update related code CSS / JS
- [x] Create samples of all possible states and variants
- [x] Create Code/Implementation guidelines
- [x] Implement pageRange = auto based on viewport (responsive)
- [x] Create VRT
- [x] Test code visual and functional for optimized viewports (only one browser): 320px, 375px, 480px, 768px, 1024px, 1366px, 1920px
- [x] Test code visual and functional for all supported browsers in viewports: 320px, 480px, 760px, 1000px, 1300px, 1760px, 1920px

// QA
- [x] 3rd party design sketch review
- [x] 3rd party design docu review
- [x] 3rd party code review (not Ole)
- [x] 3rd party code docu review
- [x] Code docu review by design 
- [x] Merge corresponding Abstract branch to master 
- [x] Export sketch lib file for deployment
