### ISSUE TITLE
Dockerise Visual Regression Testing

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#14]
**Scope**  
Visual Regression Tests have to be dockerized so that those work reliable across any operating sytem, machine and CI/CD pipeline.

**Notes**  
- Use the My Porsche Visual Regression Tester npm package of the Porsche UI NPM registry
- Dependency: Work with Christoph Stickel from Portal Services

**Subtasks**  
- [x] Setup VRT docker
- [x] Include dockerized testing into build process
- [x] Test VRT docker and workflow
- [x] Create documentation
