### ISSUE TITLE
Create Component / Text List

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#140]
**Scope**  
Create text list component with different types.

**Abstract**
https://share.goabstract.com/19620ea9-a53c-4f60-b777-67632f27922a

**Notion Link**
https://www.notion.so/porscheui/Text-list-cb09520e72f543fa97e1039c2e3fa349

**Props**
- Name: Text List
- States: default
- Variants: ordered (numeric & alphabetic), unordered
- Themes: light + dark

**Subtasks**  
// DESIGN
- [x] Move from Prep to Web library
- [x] Sketch refactoring: Adaption of new layer/text styles, spacings and icons
- [x] Sketch structure: Check override options (integrate emojis, check wording etc.)
- [x] TBD: Layout behaviour for multi-line bullets (→ stacked group?)
- [x] Approve UI definition
- [x] Create sketch library symbols and merge in Abstract
- [x] Definition of hierarchy structure and naming of all related states and variants in design
- [x] Adjust Text List based on DEV / DESIGN feedback
- [x] Create test .sketch file for community
- [x] Ask community about their preferred solution for sketch
- [x] Create must-have design docu including (optionally create and upload assets)
- [x] Remove elements from prep library (optional)

// DEV
- [x] Create/update related code CSS / JS
- [x] Create samples of all possible states and variants
- [x] Create Code/Implementation guidelines 
- [x] Create VRT
- [x] Test code visual and functional for optimized viewports (only one browser): 320px, 375px, 480px, 768px, 1024px, 1366px, 1920px
- [x] Test code visual and functional for all supported browsers in viewports: 320px, 480px, 760px, 1000px, 1300px, 1760px, 1920px

// QA
- [x] 3rd party design sketch review
- [x] 3rd party design docu review
- [x] 3rd party code review
- [x] 3rd party code docu review
- [x] Code docu review by design 
- [x] Merge corresponding Abstract branch to master 
- [x] Export sketch lib file for deployment
