### ISSUE TITLE
Basis setup stenciljs

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#143]
**Scope**  
Setup the basis structure and configuration for using stencil components

**Subtasks**  
- [x] Structure different Workshops (directories)
- [x] Setup/Install StencilJS in Workshop
- [x] Setup README.MD
- [x] Add ui-kit-js to global build task
- [x] Move Design Specs to ui-kit-js
- [x] Provide props table
