### ISSUE TITLE
Create Component / Switch

### ISSUE THREAD

**Issue by annakrohmer** [porsche-design-system/porsche-design-system#146]
**Scope**  
Create switch (a.k.a. "toggle") component. For some teams (Portal Services) it is the last remaining form element from UI Kit v0 and would be necessary to get rid of it.

**Notes**
- Create component as button
- Context examples ([UI Kit](https://designsystem.porsche.com/v0/core/?p=molecules-toggle), [App](https://share.goabstract.com/29c3c349-b3ea-4219-8b9b-692d62425bd6?collectionLayerId=053fda3c-60c5-4248-a8a3-a5c50aa86ca6&mode=design), [Modal compare](https://share.goabstract.com/9a0164d5-98ad-4ab7-abd8-f42b2b68ff43?collectionLayerId=30845977-f47d-47da-af60-86309e751323&mode=design), [E-Performance](https://www.porsche.com/germany/aboutporsche/e-performance/charging-bev/#home~open)
- Best Practices ([Apple](https://developer.apple.com/design/human-interface-guidelines/ios/controls/switches/), [Carbon](https://www.carbondesignsystem.com/components/toggle/code/), [Material](https://material.io/components/selection-controls/#switches)...) 
- Research: https://www.notion.so/porscheui/Switch-cbb7f3cf81cb49aab969c6a228e68314
- Abstract: https://share.goabstract.com/ed29a6b7-ef5b-4b46-81a8-494b04839e9e
- Accessibility: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Switch_role + https://inclusive-components.design/toggle-button/

**States**: On/Off, Disabled, Loading
**Label position**: Left + right aligned
**Stretching**: Depending on the use case, the spacing between the switch and the label can be increased. However, the minimum spacing of 8 px should be observed.

Acceptance criteria
---
- [x] Make Switch available as button
- [x] Document interaction flows in usage guideline for switch (success/error case, ...)

**Subtasks**  

- [x] Research
- [x] Draft Component (Prototyp, TBD!)
- [x] Discuss within Team (with at least one team member)
- [x] Write Usage guideline (draft)
- [x] Write Usage guideline
- [x] Create Switch component
- [x] include word-break into p-headline
- [x] include word-break into p-text
- [x] test word-break vrt in switch / text / headline
- [x] add hover test?
