### ISSUE TITLE
Optimize UX Pin Components

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#1466]
Scope
---
Make all components work as expected in UXPin and make the usability easier for the designer experience.

Notes  
---
- For some components (TextList/Flex/Grid/..) changes in props after the initial load are not reflected in the component after a change. See p-grid for gutter prop

**uxpinbind Switch**
<img width="845" alt="Bildschirmfoto 2021-07-01 um 10 27 42" src="https://user-images.githubusercontent.com/4380295/124135533-2e2a6280-da84-11eb-8df7-7a611d9e5ae0.png">

Acceptance criteria
---
- [x] Fix components
- [x] Optimize components where possible

Subtasks
---
- [x] Timebox: Check prop change reflecting after initial load (e.g. TextList)
- [x] Checkbox / Radio / Select / Text Field / Text Area: Observe required state to reflect changes immediately
- [x] Modal: Use [uxpinbind](https://www.uxpin.com/docs/merge/adjusting-components/#interaction-triggered-on-property-change) to ~trigger toggle interaction (show/hide)~ set `open` prop via `onClose`
- [x] Banner: Provide UXPin prop as wrapped function to sets the slotted content for Title and Description (don't use HTML in children)
- [x] Modal: Preset with nested elements (don't use HTML in children)
- [x] Switch: Use [uxpinbind](https://www.uxpin.com/docs/merge/adjusting-components/#interaction-triggered-on-property-change) to toggle `checked` property 
- [x] Tabs: Preset with 2 nested elements TabsItem and predefined label property + active tab 0
- [x] Text: Property for custom-size (type scale variables) + auto set to inherit if selected
- [x] ~Tabs Item label change is not reflected in edit mode (reload required)~ Bug in `p-tabs` #1506
- [x] Add active event/state for button/link pure
- [x] Modal open prop rausnehmen, click auf close darf open prop nicht ändern (uxpinbind wieder rausnehmen)
- [x] ~Banner click auf close darf nicht schließen. Interaction muss durch nutzer gesetzt werden~
- [x] ~Using 'uxpinRef' for wrapping jumping components inside a div (Banner / Button Group) (https://www.uxpin.com/docs/merge/adjusting-components/#resizing-components)~
- [x] ~Wrapping divider to enable vertical property (currently margin 0)~
- [x] ~table sorting not work anymore with preset~
- [x] ~nested tabs (tabs in another tabs item) are broken: shows tabs items (Label and content) of nested tabs in the parents tab (https://app.uxpin.com/edit/8874535#?id_page=140241783)~ Bug in `p-tabs` #1506
- [x] Add a simple HTML wrapper (e.g. div) component with all available interactions, allows nesting (children elements) and a prop field to add custom css that's gonna be reflected (e.g. background:#000; border:1px solid #000;) to increase the flexibility for advanced nestings
