### ISSUE TITLE
Audit general form patterns & elements Porsche

### ISSUE THREAD

**Issue by annakrohmer** [porsche-design-system/porsche-design-system#147]
**Scope**  
Audit most used Porsche forms and match with benchmarkings and research studies to define PAG form patterns with proper usage of  form elements. Use findings to document guidelines how to use forms at Porsche and for form elements definitions.

**PAG Forms**  
MOVES vehicle management (internal): https://k-moves.porsche.biz/mitarbeiterportal/public/index.php/reservations/form/dienstfahrt
PID Address widget: https://share.goabstract.com/dee04e8d-1688-4c95-a4ef-f8dcb50b3710
Model Page (Mobile) https://udg.invisionapp.com/share/59S7NWCPXYE
Model Page (Desktop) https://udg.invisionapp.com/share/4TS080ID3J2
Car Config (Desktop): https://udg.invisionapp.com/share/SFS6YY0GQJN 
Finder (Desktop): https://udg.invisionapp.com/share/R4S6YXC6AZP 
Newsletter (Desktop): https://udg.invisionapp.com/share/KPS13AMZGJT und https://contact.porsche.com/germany/dialog/newsletter/subscribe/

**Notes**
- UDG Forms Research: 
[2019-05-27_NextZenfo-Schulterblick.pptx](https://github.com/porscheui/porsche-ui-kit/files/3231459/2019-05-27_NextZenfo-Schulterblick.pptx)
[PDF Version](https://github.com/porscheui/porsche-drive/blob/master/Form%20Elements/2019-01-21_Recherche-Zusammenfassung_V2.pdf)
- Home & Navigation Global Animation Concept: https://highway.porsche.com/confluence/pages/viewpage.action?pageId=53765946 
[05_Global Animation Concept - Form Element – Input TextField.zip](https://github.com/porscheui/porsche-ui-kit/files/3320642/05_Global.Animation.Concept.-.Form.Element.Input.TextField.zip)
- Basis: Form Elements research PDF of "Next Zenfo" team
- Design alignment with porsche.com Team required → "Next Zenfo" project, work in progress
- TBD: 
→ What form patterns are relevant?  
→ Which form types should be described? 
→ Visual guidelines (e.g. multi-column forms y/n?)
→ …

**More info (general links / research)** 
* https://medium.com/@carolinalina/the-ultimate-guide-for-form-design-the-perfect-form-acea20367ed1
* https://blog.prototypr.io/8-rules-for-perfect-form-design-4da09b0cc79
* https://www.nngroup.com/articles/required-fields/
* https://userlutions.com/blog/usability-insights/inline-validation/
* https://www.awwwards.com/awwwards/collections/forms-and-conversational-interfaces/

**Notion Collection Link**
https://www.notion.so/porscheui/Forms-e6e2cc5d8841443da08a7c7c6d8f4ab8

**Subtasks**  
- [x] Research and definition of overall forms pattern placement in UI Kit storefront
- [x] Collect use case based form patterns and necessary form elements and map component issues
- [x] Consolidate overall form pattern guideline proposal based on research and testing
- [x] Organize workshop in UX Guild (+feedback)
- [x] Consolidate feedback of workshop and note must changes
