### ISSUE TITLE
Setup Deployment to GitHub Pages

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#15]
**Scope**  
Setup the Deployment of the Porsche UI Kit repositories to GitHub pages including the defined structure of branches and version releases.

**Out of Scope**  
GitHub Repo setup and GitHub Actions

**Notes**  
- Branches are published with branch-name for v0.x ``issue/number/core|react`` or for v1.x ``issue/number``  in the URL, e.g.
https://porscheui.github.io/porsche-ui-kit/issue/70/v1.x/
https://porscheui.github.io/porsche-ui-kit/issue/15/v0.x/core/
https://porscheui.github.io/porsche-ui-kit/issue/4/v0.x/react/
- V0 Masters are released with Circle Tag ``v.0.x/core or v0.x/react``, e.g.
https://porscheui.github.io/porsche-ui-kit/v0.1.5/core/
https://porscheui.github.io/porsche-ui-kit/v0.2.0/react/
- V1 Masters are released with Circle Tag ``v1.x``, e.g.
https://porscheui.github.io/porsche-ui-kit/v1.0.0/
- Implement pushing the latest/matching Sketch Master from Abstract to PR branch as merge condition
- Update .XML sketch URL with Master branches version tag (0.x & 1.x)
- Deploy latest sketch and changed .xml from PR branch to Github Pages

**Subtasks**  
Add all related subtasks to be completed in order to finish the issue.
- [x] Setup automated deployment of master and branches to GitHub Page
- [x] Setup versioned deployment by Git tag
- [x] Move .sketch file and xml from design kit repo to ui kit repo
- [x] Test automated deployment pipeline
- [x] Create forwarding to latest master version from home route
- [x] Configure ui.porsche.com to be used via https on GitHub.io
- [x] Deploy older UI Kit releases manually
- [x] Update PR template so that it's an acceptante criteria to copy over Sketch lib from abstract into commits of PR
- [x] Update Issue template with Abstract collection link and Abstract Workflow in GitHub Wiki
- [x] Fix issue with invisible Sketch Library Porsche logo
- [x] Fix issue with links in older UI Kit React releases
- [x] Document pipeline workflow in GH wiki
