### ISSUE TITLE
Add Angular + React Tab in Code Examples

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#152]
**Scope**  
Add automatic display of Angular + React + JavaScript code example into storefront as simulator (no real components)

**Subtasks**  
// DEV
- [x] Add React Tab
- [x] Add Angular Tab
- [x] Add JavaScript Tab
- [x] Add relevant automated tests (VRT, Unit, E2E)

// QA
- [x] 3rd party code review
- [x] Manual Browser Testing

// QA Notes
- [x] Add button to tabs for better accessibility
- [x] Remove public declarations

// Dev Notes
- [x] Code Block generation is not compatible with browsers that are not supporting Web Components natively like IE11 or Edge!
