### ISSUE TITLE
Create Style / Colors

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#16]
**Scope**  
Research on the right UI definition for colors and finalizing all colors related styles including an alignment with other touchpoint responsibilities (app, vehicle).

**Notes**  
- Use same status colors with vehicle: YELLOW #e2b236 , WARN RED #ff0000 , GREEN #13d246
- Basis White background
- Minimize the number of greys and order them with correlated contrast steps
- Remove unused colors, i.e. phantom blue

**Subtasks**  
- [x] Create UI decision proposal based on research and testing
- [x] Definition of hierarchy structure and naming of all related states and variants in design and code
- [x] Definition of focus color: https://github.com/porscheui/porsche-ui-kit/issues/69
- [x] UI definition approved

**― Design**
- [x] Create UI/UX guidelines as .md 
- [x] Include corresponding pictures in UI/UX guideline
- [x] Create/update Sketch library symbols & swatches in color picker (basic library)
- [x] Check/update all Layer Styles with new color set (basic library)
- ~~Check/update all previously built symbols in Sketch with correct colors / layer styles (web library)~~ → Makes more sense to do that later on when working on the respective components.
- [x] Update porsche-ui-kit-layout-template.sketch (theme background colors) and replace download file on server

**― Development**
- [x] Create/update related styles (CSS) and component (JS)
- [x] Create samples of all possible states and variants
- [x] Create Code/Implementation guidelines as .md for corresponding component code
- [x] Move color component to ui-kit-js
- [x] Create VRT and Unit test
