### ISSUE TITLE
Storefront / Check & optimize images in design docu

### ISSUE THREAD

**Issue by annakrohmer** [porsche-design-system/porsche-design-system#161]
**Scope**  
Images that are integrated in the design documentation should all match with our guidelines (CI / accessibility). 

**Notes**  
Check and harmonize all existing images regarding:
- Font size & color (accessibility)
- Image size
- Use real context with real text examples if necessary

**Abstract link**
https://share.goabstract.com/1ae61234-27f0-4dc9-bf6b-6e13dac91279

**List of images to be created**
- [x] Porsche marque (with and without trademark, Don'ts)
- [x] Button Regular (Button regular vs. small, Button position + example of use)
- [x] Button Icon (Example of use, Don'ts)
- [x] Text link (text on image, text link group, text link additional subtext)
- [x] Text list (Available variants – ordered vs. unordered)
- [x] Pagination (Example of use, current page, displaying 8 pages or more)

**Subtasks**  
// DESIGN 
- [x] Check and harmonize all images
- [x] Optional: Adjust storefront image layer/text styles in Sketch file
- [x] Update images on v1 branch

// REFINE
- [x] Create image collages because of image width limitation
- [x] Add best practices chapter with image collages to design docu

// QA
- [ ] 3rd party review
