### ISSUE TITLE
Migrate Storefront from React to Vue

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#164]
**Scope**  
Migrate the current scope of the react storefront to vue.

**Notes**
- Use as many web-components as possible (headline,text,textlink, button, ...)

**Out of scope**
- Modify any of the existing layout
- Live rendering of the component code

**Subtask**
// DEV
- [x] Create project structure in vue
- [x] Create storefront components (example, sidebar, markdown, story, header, footer)
- [x] Create tab navigation for code examples to show JS-markup (copy&paste solution) => will be done in #152 
- [x] Create pages and components.ts for sidebar navigation generation
- [x] Create feature toggle based on session storage
- [x] Adjust VRT testing including testingpages
- [x] Adjust E2E testing

// QA
- [x] Code walkthrough
- [x] Browsertest IE11 (not components)
