### ISSUE TITLE
Refactor Flex to web component

### ISSUE THREAD

**Issue by o-hook** [porsche-design-system/porsche-design-system#165]
**Scope**  
Refactor React Flex component to native web component

**Props** (if relevant)  
- all from React component

**Subtasks**  
- [x] Create/update related code CSS / JS
- [x] Create samples of all possible states and variants
- [x] Create Code/Implementation guidelines 
- [x] Create VRT
- [x] Test code visual and functional for optimized viewports (only one browser): 320px, 375px, 480px, 768px, 1024px, 1366px, 1920px
- [x] Test code visual and functional for all supported browsers in viewports: 320px, 480px, 760px, 1000px, 1300px, 1760px, 1920px

// QA
- [x] 3rd party code review
