### ISSUE TITLE
Refactor Spacing component to global css utility classes

### ISSUE THREAD

**Issue by o-hook** [porsche-design-system/porsche-design-system#168]
**Scope**  
Refactor Spacing component and update docs. Make Spacing classes global.

**Notes**  
- Usage of Spacings cannot be provided as a web component itself, but only as global CSS classes.

**Subtasks**  
- [x] Create/update related code CSS / JS
- [x] Create samples of all possible states and variants
- [x] Create Code/Implementation guidelines 
- [x] Create VRT
- [x] Test code visual and functional for optimized viewports (only one browser): 320px, 375px, 480px, 768px, 1024px, 1366px, 1920px
- [x] Test code visual and functional for all supported browsers in viewports: 320px, 480px, 760px, 1000px, 1300px, 1760px, 1920px

// QA
- [x] 3rd party code review

QA Notes:
- [x] zero spacing description is missing in code examples
- [x] an example that shows how to reset a spacing depending on viewport is missing
- [x] documentation of spacing scss variables and mixins is missing
- [x] documentation for auto spacing is missing
- [x] should we have '--' in classnames without BEM context (…it's just a util class)?
- [x] Add easy posibility to reset a responsive spacing and adapt vrt test
