### ISSUE TITLE
Design Guideline / Spinner

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#175]
**Scope**  
Create design documentation for the Spinner Component

**Subtasks**  
- [x] Create design documentation
- [ ] Create and upload assets
- [x] Proofreading
- [ ] Feedback round with community (optional)

// QA
- [ ] 3rd party docu and assets review
