### ISSUE TITLE
Spike: Code Preview by SaaS for VanillaJS, Angular, React and NextJS

### ISSUE THREAD

**Issue by denyo** [porsche-design-system/porsche-design-system#1799]
Scope
---
To simplify the process of reproducing and reporting bugs by our community we should provide a CodePen / StackBlitz / Sandbox / jsFiddle (or similar) with a basic VanillaJS, Angular, React and NextJS setup so that they can reproduce their issue easily and share it. Evaluate if it is better than a sample repo.
In addition evaluate possibilities to replace actual code examples within storefront with e.g. CodePen / StackBlitz / Sandbox / jsFiddle (or similar) with a basic VanillaJS, Angular, React and NextJS setup.

Notes
---
- Probably it makes things easier as soon as `@porsche-design-system/components-js|angular|react` npm package is public available.

Acceptance criteria
---
- [x] Tools are evaluated for reproducing / sharing errors in VanillaJS, Angular, React and NextJS to decide which implementation to choose in a follow up issue.
- [x] Tools are evaluated for sharing code examples within storefront for VanillaJS, Angular, React and NextJS to decide which implementation to choose in a follow up issue.

Subtasks
---
- [x] Create Ticket for Edit in StackBlitz button for all frameworks https://github.com/porscheui/porsche-design-system/issues/1951
- [x] Create Ticket for StackBlitz Bug Template in Github implementation https://github.com/porscheui/porsche-design-system/issues/1952
- [x] Create Ticket for Global theme + framework switcher https://github.com/porscheui/porsche-design-system/issues/1953
- [x] Check if static code with highlighting could be provided from StackBlitz -> StackBlitz does not Provide a solution like that
- [x] Check tsx option in prism to improve code highlighting https://github.com/porscheui/porsche-design-system/issues/1419

Findings
---
| Tools              | Costs of usage    |                                                                                             | supported frameworks |       |         |        | npm package usage                                                                                       |
| ------------------ | ----------------- | ------------------------------------------------------------------------------------------- | -------------------- | ----- | ------- | ------ | ------------------------------------------------------------------------------------------------------- |
|                    | free              | cost                                                                                        | vanillaJs            | React | Angular | NextJs |                                                                                                         |
| ------------------ | ----------------- | -----                                                                                       | -------------------- | ----- | ------- | ------ | -----------------                                                                                       |
| CodePen            | Public projects   | $720 / year for private pens to display on storefront                                       | ✓                    | ✓     | ✗       | ✗      | Uses Skypack cdn to import packages. Does not work out of the box and throws jsx error while importing. |
| StackBlitz         | Public projects   | $495 / year for 5 devs + unlimited private projects (Enterprise plan needs to be requested) | ✓                    | ✓     | ✓       | ✓      | Easy to use, no auto completion                                                                         |
| CodeSandbox        | Public projects   | $420 / year for 5 devs                                                                      | ✓                    | ✓     | ✓       | ✓      | Easy to use import with auto completion                                                                 |
| jsFiddle           | Public projects   | $90 / year per developer for private fiddles                                                | ✓                    | ✓     | ✗       | ✗      | No out of the box solution, needs something custom like unpkg.com                                       |

| Tools       | embedding                                                                                                                                                                                      |
| ----------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| StackBlitz  | Easy embedding, provides sdk which allows to embed or open in new tabs. On top possibility of github repo embedding -> as soon as we are public we can use it for our angular + react examples |
| CodeSandbox | Embedding via iframe, similar to StackBlitz but without files out of repo embedding                                                                                                                                 |

Concerns:

- Third party application means loading time. Switching between examples takes time.

Conclusion:

- StackBlitz embeding would work for all existing examples, but there are performance issues. Thus we will use StackBlitz for the edit on button and for our Bug reporting repos.
- Free version should be enough for templating / edit in button
