### ISSUE TITLE
Create Component / Icons V1

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#18]
**Scope**  
Research an appropriate way to create a React component for Icons and finalize a version to be included in the Porsche UI Kit react. Opzimize current icons for new dimensions in code and design.

**Notes**  
- Name Icons according to naming convention: https://github.com/porscheui/porsche-ui-kit/files/3146855/190228_Porsche_Icons_Prozess-Interation2.pdf
- Dont use Icon repository to store SVGs, use existing solution?
- Current Web Icon Scope: https://github.com/porscheui/porsche-ui-kit/files/3146826/Porsche_Web_Icons_48_v1.0.sketch.zip

**Notion**  
- https://www.notion.so/porscheui/Iconography-d2cb2356524d4783947e3092df164f20

**Subtasks**  
// DESIGN
- [x] Include and Test Iconset and collect feedback
- [x] Refactor SVGs based on old icon set
- [x] Create branch in Abstract according to issue number, update sketch library and add collection link issue
- [x] Create must-have design docu including (optionally create and upload assets)
- [x] Remove elements from prep library (optional)

// DEV
- [x] Finalise research about technical solution and decide on
- [x] Create/update related styles (CSS) and component (JS)
- [x] Merge relevant WebIcon set definition from old icon set to new library
- [x] Provide icons as x1 (24x24), x1.5 (36x36) and x2 (48x48)
- [x] Refactor icon component as webcomponent
- [x] Create Code/Implementation guidelines: include how to replace the default icon
- [x] Add pixel dimension to component headline: small (24px), medium (36px), large (48px)
- [x] Include icons from UI Kit CDN
- [x] Test code visual and functional for optimized viewports (only one browser): 320px, 375px, 480px, 768px, 1024px, 1366px, 1920px
- [x] Test code visual and functional for all supported browsers in viewports: 320px, 480px, 760px, 1000px, 1300px, 1760px, 1920px

// QA
- [x] 3rd party design sketch review
- [x] 3rd party design docu review
- [x] 3rd party code review (not Ole)
- [x] 3rd party code docu review (not Ole)
- [x] Code docu review by design 
- [x] Merge corresponding Abstract branch to master and export sketch lib file for deployment
