### ISSUE TITLE
Provide "Grid Main" as part of utilities sub package

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#1805]
Scope
---
The newly spiked **Grid Main** (https://github.com/porscheui/porsche-design-system/pull/1796/files#diff-9fc1861bde588e16bf5e99a2aa155d5b43b322493e9d26a53b1203da79f70ef5R43) shall be provided by a utility style function to reduce Layout Shift and increase overall UX of an application integrating the Porsche Design System.

Out of Scope
---
- No documentation required for now.
- No grid patterns shall be provided (will be done in a follow up issue)
- No VRT test setup

Notes
---
- Evaluate a proper utility function name.
- Spike was already done by @stephanschroeter 

Acceptance criteria
---
- [x] **Grid Main** is available by utilities sub package
- [x] **Grid Main** is supported by `scss`, `styled-components`, `jss`

Subtasks
---
- [x] Simplify grid gutter + grid safe zone to one variable
- [x] Create abstract example pattern with new grid
- [x] Use new grid gutter + grid safe zone in components (e.g. modal, ~~grid~~, banner, modal, toast…)
- [x] Create real example pattern with new grid
- [x] Grid utils docs? => #1866 
- [x] flex, grid, content-wrapper deprecation in storefront? => #1866 
- [x] finder, drive, shop, my porsche pattern page in storefront? => #1984
- [x] full size module above 1920px vw placed within grid with background color?
- Preview Link of integrated new grid: https://designsystem.porsche.com/issue/1805/patterns/apps/example/porsche-com
