### ISSUE TITLE
Design Guideline / Layout

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#187]
**_→ Merge with issue #657_** 

---

**Scope**  
Create overall design documentation for general layouting principles, e.g. boxing vs. floating.

**Notes**
- Layout types (content page, table)
- Alignments
- Layout templates

**Subtasks**  
- [ ] Audit and benchmark most important contents and structure
- [ ] Create design documentation
- [ ] Create and upload assets
- [ ] Proofreading
- [ ] Feedback round with community (optional)

// QA
- [ ] 3rd party docu and assets review
