### ISSUE TITLE
Font Next & Next Auto audit, test and alignment

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#189]
**Scope**  
Use the Porsche Next Auto TT for web application context screens and within the UI Kit components and document improvement requirements for an alignment meeting over all touchpoints. Goal: reduce 2 fonts and use only 1 for all touchpoints vehicle, app, web.

**Notes**  
- Use different context screens: Light/Dark, Content-Page/Application-Page, Mobile/Tablet/Desktop
- Check major UI comonents: Buttons, Typography, Textlist/Link
- Porsche Next Auto TT (OTF / TTF)

**Subtasks**  
- [ ] Decide on key screens to implement and for testing
- [ ] Briefing and setup testing cases
- [ ] Create context screens
- [ ] Highlight aesthetic issues of Next Auto TT as adjustment briefing
- [ ] Perform quick poll preference test
- [ ] Perform usability test: readability
- [ ] Decide alignment
