### ISSUE TITLE
Define Porsche UI Kit source structure and configuration

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#19]
**Scope**  
For the Porsche UI Kit 1.0 release the internal development/testing (SRC) and consumer facing visualization structure (Documentation/App) should be defined as well as the development configuration.

**Out of Scope**  
- Definition of the component structure and naming of the source structure

**Notes**  
- Research about Storybook or other possibilities to develop and visualize

**Subtasks**  
- [x] Research about storybook setup possibilities to suggest a possible usage concept
- [x] Decide on tool setup
- [x] Add package.json config
- [x] Add browserlist config
- [x] Add .nvmrc
- [x] Add .npmrc
- [x] Add TsLint config
- [x] Add Tsconfig
- [x] Add Prettier and PreattierIgnore config
- [x] Add Stylelint config (based on AirBnb)
- [x] Add Editor config
- [x] Add README.md
- [x] Add Definition Of Done (in WiKi)
- [x] Document all decisions and relevant information in Github Wiki
