### ISSUE TITLE
Generating of react specific components

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#191]
**Scope**  
Generate react components and review / test them within the Porsche UI Kit and integration with consuming teams

**Notes**  
- Polyfill issue to be completed #167 

**Subtasks**  
// DEV
- [ ] Create integration pages for angular and react
- [ ] Create VRT test for framework integration
- [ ] Create browser test - especially IE11

// QA
- [ ] 3rd party code review
- [ ] Review with consumer teams
