### ISSUE TITLE
Generating react specific components

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#193]
**Scope**  
Generate react components and review / test them within the Porsche UI Kit and integration with consuming teams

**Out of scope**
- React bug: #251

**Subtasks**  
// DEV
- [x] Create integration pages for react
- [x] Add VRT test of component overview page for react
- [x] Resolve problems in starting react test project

// QA
- [x] 3rd party code review
