### ISSUE TITLE
Generating angular specific components

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#194]
**Scope**  
Generate angular components and review / test them within the Porsche UI Kit and integration with consuming teams

**Note**
- IE11 testing must be ensured by #206 

**Subtasks**  
// DEV
- [x] Create angular package for automated component creations
- [x] Create integration pages for angular
- [x] Create VRT test for framework integration

// QA
- [x] 3rd party code review
