### ISSUE TITLE
General Layout Guidelines

### ISSUE THREAD

**Issue by oliviapala** [porsche-design-system/porsche-design-system#196]
**Scope**
Create general Layout Guidelines documentation 

**Subtasks**

- [ ]Create design documentation
- [ ]Proofreading
- [ ]Feedback round with community (optional)
// QA

- [ ]3rd party docu
