### ISSUE TITLE
Setup Storefront for Porsche UI Kit APP

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#197]
**Scope**  
In order to publish the guidelines and component documentation for the Porsche UI Kit (native) app, we want to extend the web storefront (Design-System) by a subdirectory for app. The goal ist to onboard the App Framework team, to publish their documentation using the same storefront technology.

**Out of Scope**  
- No clone or seperate setup for app documentation storefront
- The App storefront wont visualize and publish coded components - only design docu
- Different versioning for App
- No storefront toggle between App / Web

**Notes**  
- The web contents should be available with ui.porsche.com/web/ and is the standard startpage of ui.porsche.com
- The app contents should be available with ui.porsche.com/app/
- For the App storefront we only need guideline / information pages and design docu pages on component level
- App must use the versioning of UI Kit web for now

**Subtasks**  
// DEV
- [x] Setup seperated web / app structure within design-system
- [x] Change URL paths and deployment process
- [x] Create Dummy Pages for App Storefront

//QA
- [x] 3rd Party review code
- [x] Check all static links inside Storefront documentation files

//QA Notes
- [x] Split design system config into two separate ones (web & app)
- [x] App design system config should only contain "Pages" as configuration object
