### ISSUE TITLE
Create docu for Slack / Community Sync / Browsersupport

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#20]
**Scope**  
Create docu for Slack / Community Sync / Browsersupport as .md in GitHub Wiki

**Subtasks**  
- [x] Create docu for Slack Administration
- [x] Create docu for Community Sync Administration
- [x] Create docu for Browsersupport
