### ISSUE TITLE
Icon Tool / Add Download functionality

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#200]
**Scope**
Add the feature to download the selected icon or the complete set based on the currently selected category filter

**Notes**
- Only provide ZIPed packages to download for categories brand/vehicle and filled/outline (4 variants)

**Tasks**
// DEV
- [ ] include basic svg icon download as first step
- [ ] Include download functionality for downloading 4 different package variants
- [ ] Include download functionality for single icon (it's also a ZIP containing svg and png)

// QA
- [ ] 3rd party code review
