### ISSUE TITLE
Icon Tool / Frontend extension and beautification

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#201]
**Scope**
Add an icon details view (onclick on single icon item) and adjust the overview page of icons and icon items according to UI definition.

**Notes**
- Use as much web components as possible, e.g. icon component for displaying icons
- Good example: https://ionicons.com/
- Setup tests without relation to specific icon (always use 1st item)

**Tasks**
// DEV
- [x] Add overlay/view for relevant icon item JSON fields (name, description, download links, etc.)
- [x] Adjust frontend UI of icon overview and icon items
- [x] Adjust elements
- [x] Invert download icon in icon items on overview in dark mode
- [x] _Add redirect to home for all possible urls (404) (see comment below)_
- [x] Add text "no icons found" to filter
