### ISSUE TITLE
Establish automated IE11 VRT testing

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#206]
**Scope**  
Integrate IE11 VRT tests

**Notes**  
- Must also work for native Angular and React
- Medium article like a bo$$: https://medium.com/vincent-ogloblinsky/cross-browser-testing-your-stencil-web-component-like-a-boss-93c1b154bfd9

**Subtasks**  
// DEV
- [x] Research concepts of Browserstack screenshot testing API with VRT support 
- [x] Decide on IE11 testing concept
- [x] Create new Github repository for VRT with Browserstack Screenshot API (based on VRT Tester)
- [x] Develop configurable testing script which uses Browserstack Screenshot API to make, save and compare screenshots
- [x] Create concept how to handle Browserstack username/key within VRT package.
- [x] Crop Browserstack watermark (with Gimp) from screenshot before shots are compared.

// QA
- [x] Fix UI Kit platform behavior
- [x] 3rd party code review
