### ISSUE TITLE
Extend component test coverage for 1.0 alpha

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#207]
**Scope**  
Create additional minimal required tests (critical bug risk) for a better test coverage for a alpha 1.0 release.

**Out of Scope**  
- not critical test cases
- Storefront tests

**Note**
Actually there is a bug in Stencils pre configured  jest test suite: https://github.com/ionic-team/stencil/issues/1609

Maybe it is better to setup unit testing by ourselfs: https://medium.com/@tally_b/unit-testing-stenciljs-1-0-c4e902a4e63c

Another good article about unit testing in Stnecil: https://www.joshmorony.com/the-basics-of-unit-testing-in-stencil-js/

**Subtasks**  
// DEV
- [x] Add basic test setup
- [x] Establish basic set of tests which might be used as astandard for all components
- [x] Add unit tests for pagination component to test rendering and logic.
- [x] Create more specific tests for all components

// QA
- [x] 3rd party code review
