### ISSUE TITLE
Enable SSR/SSG for NextJS

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#2087]
Scope
---
Follow up of #1221, we want to implement a reliable and tested solution for supporting SSR/SSG with (re)hydration of our React components for Next JS.

Notes  
---
- Maybe it's necessary to either create a separate next-js components package or extend the react components package and create a new one for uxpin components.

Acceptance criteria
---
- [x] SSR/SSG with (re)hydration of PDS components is supported and tested by test automation in Next JS

Subtasks
---
- [x] Markup of PDS components is renderable on Node server within React component wrapper
- [x] Specific Custom Element features (like e.g. `<slot/>`, named slots
- [x] attributes on `<host/>` element, etc.) are replaced by supported alternative ways of a React component
- [x] Styles of PDS components are renderable on Node server within React component wrapper
- [x] Specific Shadowed Styles (e.g. `:host`, `::slotted`, etc.) are replaced by supported styles that live in Light Dom
- [x] Styles are scoped in Light Dom until PDS components are hydrated with Shadow Dom
- [x] remove useless `:hover` and `:focus` styles
- [x] Test automation ensuring markup+styles functions are bundled only in server build not in client build in Next JS is in place
- [x] VRT Tests for all PDS components for Next JS with disabled JavaScript are in place
- [x] NextJS/React warnings regarding e.g. unmatched server and client markup is suppressed 
- [x] solve references to `this.host`
- [x] solve references to `this.select`,  `this.input` and `this.textarea`
- [x] ~~solve private members like `this.isSearch`~~
- [x] solve `window`, `document`,`el.querySelector` and `el.getAttribute` issues in components utils bundle
- [x] ~~solve references to parents (e.g. within form)~~ => nothing we can do about
- [x] ~~are jsdom-polyfills still valid as they are?~~ => postponed
- [x] try declarative shadow root
- [x] fix flash when web component hydrates
- [x] ~~ssr prop on react wrapper?~~ => should be discussed after PDS SSR is integrated into Porsche Finder
- [x] align project and dist folder  structure (`angular-wrapper`, `react-wrapper`, `react-ssr-wrapper`)
- [x] bundle and ship `react-ssr-wrapper` as `components-react/ssr` subpackage
- [x] unit test setup for `react-ssr-wrapper`
- [x] ~~what about `attachSlottedCss` (light DOM css)?~~ => we want to remove custom slotted styles completely in v3 by e.g. a `normalize.css`
- [x] ~~take care of icon svgs~~ => we want to use <img/> for svg's instead of fetching and inlining them if possible for now?
- [x] bundle and ship dsr ponyfill
- [x] ~~improve ssr carousel (need to apply classes and inline styles that splide puts on)~~ => won't do
- [x] improve ssr tabs
- [x] improve ssr scroller
- [x] improve ssr accordion
- [x] improve ssr link-tile
- [x] docs follow up task #2105
- [x] optimize rollup for 1 input, 2 outputs instead of 1 input, 1 output multiple times => https://github.com/porsche-design-system/porsche-design-system/issues/2157
- [x] extend storefront playgroud by NextJs tab with stackblitz => https://github.com/porsche-design-system/porsche-design-system/issues/2158
- [x] ~~optimize dsr ponyfill by removing redundant/unneeded code~~ => won't do for now
- [x] apply ssr components to porsche finder
- [x] add various devDependencies for rollup and plugins
- [x] check stencil core patch in safari
- [x] add missing table vrt page
- [x] playwright e2e test for safari with dsr ponyfill and bootstrapping components
- [x] remove unused ssr styles from popover, select-wrapper-dropdown, toast...
- [x] add hasEvent + eventNames into componentMeta and Mock packages/components/src/styles/hover-media-query.spec.ts for this.dismiss.emit
- [x] Try to fully support SSR for `Grid`
- [x] Revert changes for `Carousel` and update VRT
- [x] optimize components with parent/child relationships: `p-grid`, `p-text-list`, `p-tabs`, `p-segmented-control` and `p-stepper-horizotal`
- [x] Ensure with e2e test or unit test that no new line is generated in HTML file
