### ISSUE TITLE
Define Component structure and roadmap

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#21]
**Scope**  
Documentation of future Porsche UI Kit contents structure (Styles and Components) based on research with benchmark Design Systems and Testing with Consumers (Dev/Design) in GitHub Wiki for internal information.

**Out of Scope**  
- Source Code Structure
- Component Naming Definition

**Notes**  
- Structure should be easily understandable and accessible with different environments (Storybook Deployment and Sketch Library Connection)

**Subtasks**  
- [x] Finish research on content structure
- [x] Prepare decision template to be discussed in Porsche UI Team and for testing
- [x] Finish short consumer testing
- [x] Create documentation in GitHub Wiki
