### ISSUE TITLE
Optimize all textual components

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#212]
**Scope**  
In order to improve consistency of using different kind of text components it's necessary to align them. This affects: 
- p-headline
- p-text
- p-text-link
- p-text-list

**Subtasks**  
Add all related subtasks to be completed in order to finish the issue.
- [x] Align color prop / theme (only color prop should be used)
- [x] How to handle sizing (dynamic / static) (affects all components beside of headline)
- [x] Simplify code examples (especially p-text generic sizes)
- [x] Evaluate usage of p-text-link, especially in terms of style inheritance and how to use it with framework specific router
- [x] Is it clear for a consumer by reading a docu when to use which font-size (especially p-text and p-headline)

- [x] Add color prop "inherit", "porsche-black", "porsche-light" for all text components (remove theme prop), default is "porsche-black"
- [x] Implement all available size definitions for p-text-link, p-text but p-text-list which should only have default 16px (1rem) size
- [x] Optimize code examples for p-text and p-text-link generic types by visualize them via configurator 

// QA

- [x] 3rd party code review
