### ISSUE TITLE
Add automated release strategy

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#214]
**Scope**  
Replace the manual release steps by automated workflow

**Notes**  
- Must contain automated version tag for dev+design, package building, package deployment, release note
- Integrate github actions workflow and PR process
- Whenever a release of Porsche UI Kit is made, a Git tag should be set with corresponding version number, e.g. v1.1.9 and GH Actions CI/CD should detect that a new git tag was set and update the Sketch RSS feed.

**Subtasks**  
- [x] Sketch RSS feed version based on Git tag
- [x] Improve prepare-release script for components(-js/-angular/-react)
- [x] Add prepare-utilities script
- [x] Update ReadMe
- [x] Add Git Tag on master/v* branches while releasing
- [x] Write `run-release-npm` in bash
- [x] Fix CDN server on `yarn start` from root package.json
- [x] Split Sketch Lib Basic and Web into independent releasable artifacts
