### ISSUE TITLE
Move Sketch basic library to own Abstract project

### ISSUE THREAD

**Issue by annakrohmer** [porsche-design-system/porsche-design-system#217]
**Scope**  
In order to establish a single source of truth and enable other projects (first the iOS app teams) to use and edit it, we should move the Sketch library "porsche-ui-kit-basic" to an own Abstract project. 

**TBD**
Is this solution valuable in terms of a smooth Abstract workflow?
Libraries in 2 projects = need for 2 branches when working simultaneously on both libraries. Multiple files from different branches can't be edited at the same time due to Git workflow in Abstract. So we would be forced to first edit the Basic library (layer styles), release it and then link the layer styles to the Web library, which isn't practicable whilst setting up a new component.

**Subtasks**  

// Structural preparation
- [x] Clearify questions
- [x] Set up new Abstract project 
https://share.goabstract.com/21c4d4c5-2bef-465a-88a0-b87a9698f229

// Prepare basic library for transfer to new Abstract project
- [x] Split text style structure (→ level 1: Web / App)
- [x] Integrate disclaimer for App font (if possible, tbd)
- [x] Check if other splits / adaptions have to be made

// Provide new library
- [x] Export library → Import in new Abstract project
- [x] Delete former library from UI Kit project
- [x] Document changes in workflow (notion)
https://www.notion.so/porscheui/Basic-library-4bd2c61f514148c5966331cfde1f18a2

// QA
- [x] 3rd party review
