### ISSUE TITLE
Add npm package to serve SCSS utilities

### ISSUE THREAD

**Issue by o-hook** [porsche-design-system/porsche-design-system#218]
**Scope**  
To support better developer experience by providing SCSS mixins and variables, we have to add a separate npm package which can be installed by the user.

**Subtasks**  
// DEV
- [x] Extract SCSS utility files to separate folder
- [x] Release npm package
- [x] Add documentation how to use SCSS utilities in Readme
- [x] Modify SCSS documentation in storefront for color, spacing and typography
- [x] Add e2e tests

// QA
- [x] 3rd party code review
