### ISSUE TITLE
Release Porsche UI Kit 1.0.0-alpha.1

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#221]
**Scope**  
Release **Porsche UI Kit ONE** - 1.0 alpha in code / design

**Notes**  
- Test release before public release
- Document all tasks/steps as blueprint for future releases
- Start-coding should contain: 1. Request access, 2. package overview, 3. include packages, 4. example in js, angular, react
- #194 #193  must be closed

**Subtasks**  
- [x] Remove the rights for PorscheUI to fetch NPM packages remotely
- [x] Manually create and deploy 1.0.0-alpha package for ui-kit-js, ui-kit-react, ui-kit-angular and ui-kit-scss-utils
- [x] Set version tags
- [x] Change version in storefront header
- [x] Publish integration guideline at Start Coding page
- [x] Design graphic for release announcement
- [x] Write release note
- [x] Create Release Note Image
- [x] Remove feature toggle for 1.0 components
- [x] Create changelog: initial release
- [x] Share release note
- [x] Document release checklist in workflow

**Abstract**
https://share.goabstract.com/298500bc-0c0a-4bc1-bf8c-c21d1f7036e8
