### ISSUE TITLE
Visualization of GitHub workflow

### ISSUE THREAD

**Issue by annakrohmer** [porsche-design-system/porsche-design-system#224]
**Scope**  
Transfer of GitHub workflow scribble to Sketch graphic.
(Supervization only; will be executed by Andreea.)

**Abstract link**
https://share.goabstract.com/b28a58f4-bbdb-4bf4-9850-e5a6b697add8?sha=dc68d8ef3b7d7c20bd15513d1de935069464aa6c

**TBD**
Print-out in DIN A2?

**Subtasks**  
- [x] Visualisation in Sketch
- [x] 3rd party review
- [x] Share with team / documentation in notion
https://www.notion.so/porscheui/GitHub-Workflow-a4c154e3518148eaa3bf17d9f1b20af3

![IMG_1403](https://user-images.githubusercontent.com/43340739/62277388-5c413b00-b446-11e9-8f88-dea5bb1c6a22.jpg)

// Notes
- [x] "Export Sketch library and copy to GitHub Server" When does this happen?
- [x] "PR Code", it might also be an iterative process like in "PR Design"
