### ISSUE TITLE
Sketch / Adjust library template and adapt styles to basic & web library

### ISSUE THREAD

**Issue by annakrohmer** [porsche-design-system/porsche-design-system#226]
**Scope**  
In order to follow our own standards, the defined basic styles (colors/layer styles, text styles, spacing) should be adapted to both basic and web library artboards.

**Subtasks**  
// DESIGN
- [x] Check and adjust puik-template-library.sketch due to basic styles.
- [x] 3rd party Sketch review of library template.
- [x] Adapt library template to basic library. 
- [x] Adapt library template to web library.
- [x] 3rd party Sketch review of basic & web library.

// QA
- [x] Merge branch to master
- [x] 3rd Party design review
