### ISSUE TITLE
Icon Tool / Deployment of icons

### ISSUE THREAD

**Issue by mhp-borisbojic** [porsche-design-system/porsche-design-system#234]
**Scope**  
Setup build and deployment for JSON and Icons to Edgecast CDN

**Notes**  
- All added/modified/deleted icons (event the not public ones) should be automatically deployed to CDN

**Subtasks**  
- [x] Decide on CDN folder naming and URL structure for Porsche UI assets on CDN (to reference in UI Kit)
- [x] Define workflow of automated icon CDN deployment including Edgecast API research
- [x] Implement CDN deployment for icon assets to PorscheUI CDN
- [x] Setup private / public ssh keys for deployment
- [x] Setup GitHub Actions workflow
- [x] Add a technical user for Porsche CDN @o-hook
