### ISSUE TITLE
Code clean up Alpha Release

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#238]
**Scope**  
Due to alpha release, it's necessary to optimize and clean up multiple things. Have a look in the list below.

**Subtasks**  
// DEV
- [x] Separate package.json for app & lib => React (also think of doing the same for UI Kit JS)
- [x] CHANGELOG + README + LICENSE needs to be within ui-kit-angular / react / js package
- [x] Fix Porschedev Artifactory proxy
- [x] Packages can't be installed from PorscheUI Artifactory if remote-npm ist not setup
- [x] Add Feedback Board
- [x] Add note on frontpage of design system regarding feedback board and delete links to UI Kit v0
- [x] Scroll up does not work by default with Vue Router for non body scroll
- [x] Fix warnings in snapshot tests in React
- [x] Move tests folder outside of src (package.json / Jest config) => React
- [x] Move tests folder outside of src (package.json / Jest config) => Angular
- [x] Linter does not throw error on error --> Tested it local in docker env and it throws errors (SCSS and TSX) but doesn't skip following tests. `concurrently --kill-others-on-fail`doesn't seem to work.
- [x] E2E Test missing for Marque in Design System
- [x] Extract CSS Demo Styling (for JS/React/Angular)
- [x] CI/CD parallize jobs
- [x] Angular Test Automation (Jest Snapshot)

// STENCIL
- [x] React fix, replace life cycle hooks (deprecated life cycle hooks) => or ask Stencil to fix it
- [x] Don’t create angular+react build files on yarn start (stencil project) because it produces unwanted generated react wrappers (components.ts) => or ask Stencil to fix it --> This is communicated to Stencil and on their roadmap
