### ISSUE TITLE
Design Kit / Split of Core & Prep Library

### ISSUE THREAD

**Issue by annakrohmer** [porsche-design-system/porsche-design-system#24]
**Scope**  

Separation of former 1 sketch library file (porsche-ui-kit-core.sketch) into 2 files:
- Core (porsche-ui-kit.sketch)
- Prep (porsche-ui-kit-prep.sketch)

**Notes**  

Share any further information that is relevant for processing.

**Subtasks**  

Core @annakrohmer 

- [x] Copy core contents (incl. pages + symbols) into completely new (!) sketch file
- [x] Clean-up: Removing unused masks
- [x] Clean-up: Symbol Instance Renamer → Rename Instances on All Pages (Except Symbols Page)
- [x] Clean-up: Symbol Namings (remove slashes, remove blanks, dark → inverted, light → standard)
- [x] Clean-up: Overrides (block layers that shouldn't be overrides, optimize layer sequence, insert icons)
- [x] Run symbol organizer
- [x] Remove icons (⚒ etc.) from page names (won't be used in Abstract anymore)
- [x] Clean-up: Remove unused symbols
- [x] Put all inverted symbols on dark BG (#191f22) to optimize visibility
- [x] Insert library cover image
- [x] Make sure that standard and inverted components are placed on different artboards
- [x] Insert Padding functionality in Button Regular
- [x] Final Check-up
- [x] 3rd party review

Prep @oliviapala 

- [x] Copy core contents (incl. pages + symbols) into completely new (!) sketch file
- [x] Clean-up: Removing unused masks
- [x] Clean-up: Symbol Instance Renamer → Rename Instances on All Pages (Except Symbols Page)
- [x] Clean-up: Symbol Namings (remove slashes, remove blanks, dark → inverted, light → standard)
- [x] Clean-up: Overrides (block layers that shouldn't be overrides, optimize layer sequence, insert icons)
- [x] Run symbol organizer
- [x] Remove icons (⚒ etc.) from page names (won't be used in Abstract anymore)
- [x] Clean-up: Remove unused symbols
- [x] Put all inverted symbols on dark BG (#191f22) to optimize visibility
- [x] Insert library cover image
- [x] Make sure that standard and inverted components are placed on different artboards
- [x] Final Check-up
- [ ] 3rd party review
