### ISSUE TITLE
Improve Notification Color Contrast

### ISSUE THREAD

**Issue by muellernaumann** [porsche-design-system/porsche-design-system#2408]
Scope
---
Based on community feedback we would adjust the different notification color values. 

Acceptance criteria
---
The color values ​​in `light` correspond to the following:
- [x] light-notification-success: `#197E10` • `filter:invert(28%) sepia(89%) saturate(572%) hue-rotate(71deg) brightness(111%) contrast(98%);`
- [x] light-notification-success-soft:`#E4FFEC`
- [x] light-notification-warning:`#F3BE00` • `filter: invert(58%) sepia(53%) saturate(820%) hue-rotate(12deg) brightness(112%) contrast(103%);`
- [x] light-notification-warning-soft: `#FFF4D2`
- [x] light-notification-error: `#CC1922` • `filter: invert(14%) sepia(75%) saturate(4140%) hue-rotate(347deg) brightness(100%) contrast(97%);`
- [x] light-notification-error-soft: `#FFE2E4`
- [x] light-notification-info: `#2762EC` • `filter color done by tatjana`
- [x] light-notification-info-soft: `#D3E1FF`

The color values ​​in `dark` correspond to the following:
- [x]  dark-notification-success: `#09D087` • `filter: invert(60%) sepia(71%) saturate(512%) hue-rotate(106deg) brightness(91%) contrast(97%);`
- [-] dark-notification-success-soft: `#003320` --> won't be uodated because there is no change
- [x] dark-notification-warning: `#F7CB47` • `filter: invert(75%) sepia(39%) saturate(759%) hue-rotate(350deg) brightness(109%) contrast(94%);`
- [x] dark-notification-warning-soft: `#362B0A`
- [x] dark-notification-error: `#FC4040` • `filter: invert(64%) sepia(91%) saturate(5857%) hue-rotate(336deg) brightness(98%) contrast(102%);`
- [x] dark-notification-error-soft: `#3A0F0F`
- [x] dark-notification-info: `#178BFF` • `filter color done by tatjana`
- [x] dark-notification-info-soft: `#04294E`

Subtasks
---
- [x] Tasks will be done with ticket #2394 
- [x] Check filter colors on mobile safari

**Comment by o-hook** [comment]
Tasks will be done with ticket #2394
