### ISSUE TITLE
Icons / Add icon overview in storefront documentation (temporary solution)

### ISSUE THREAD

**Issue by annakrohmer** [porsche-design-system/porsche-design-system#242]
**Scope**  
Currently, we provide a (short) icon documentation and a code description on how to integrate the desired icon via source string. But currently, there's no overview available in storefront so that designers and developers know which icons (and source strings) exist at all. It's only to be seen via "Insert symbol" in Sketch library. But as long as neither the new icon tool nor the new icon set is available we should provide an overview in the storefront (workaround solution). 

**Notes**  
We should find an easy workaround solution, such as integrating the icon overview as PNG or PDF in the storefront.

**Subtasks**  
- [x] Open new GitHub issue branch.
- [x] Add icon reference to icon design docu
- [x] Push my commits to GitHub.
- [x] Open a pull request.
- [x] Change Abstract share permissions to public

// QA
- [x] 3rd party review
