### ISSUE TITLE
Sketch libraries / Clean-up Alpha Release

### ISSUE THREAD

**Issue by annakrohmer** [porsche-design-system/porsche-design-system#243]
**Scope**  
Due to alpha release, it's necessary to optimize and clean up multiple things as well as documenting them for future editing. Have a look at the list below.

**Subtasks**  

// GENERAL DEFINITIONS + DOCUMENTATIONS

- [x] Define general rules for library setup and document them as checklist(s) in notion: https://www.notion.so/porscheui/Sketch-Library-setup-a2f0711edc65497c8a3468713977c38f
- [x] Define general rules for symbol (component) setup and document them as checklist(s) in notion: https://www.notion.so/porscheui/Sketch-Component-setup-210aa34e558641d69d1b2976e8f6a3ec
- [x] Optional: Research on best practices for library and symbol setup.
- [x] Discuss general rules with design team.

// BASIC LIBRARY

- [x] Open new issue branch in Abstract (basic project).
- [x] Rename text style for symbol titles that is currently placed between app and web, which is a bit distracting:
![image](https://user-images.githubusercontent.com/43340739/63777334-3abb5e00-c8e3-11e9-900f-484941a45847.png)
- [x] Check symbols based on new upcoming notion checklist istems (optional)
- [x] Commit changes.
- [x] Request review.
- [x] Merge changes to master.

// WEB LIBRARY

- [x] Open new issue branch in Abstract (basic project).
- [x] Rename text style for symbol titles that is currently placed between app and web, which is a bit distracting:
![image](https://user-images.githubusercontent.com/43340739/63777334-3abb5e00-c8e3-11e9-900f-484941a45847.png)
- [x] Check symbols based on new upcoming notion checklist istems (optional)
- [x] Check and clean up colors / layer styles (apparently there are not only basic colors in use, had not enough time to clean that up for Alpha Release)
- [x] Commit changes.
- [x] Request review.
- [x] 3rd party design review.
- [x] Merge changes to master.
