### ISSUE TITLE
Sketch / Button Regular – Check default color for icon overrides

### ISSUE THREAD

**Issue by annakrohmer** [porsche-design-system/porsche-design-system#248]
**Scope**
When changing the icon in Button Regular symbols (from porsche-ui-kit-web.sketch library), the color changes. To avoid this it's necessary to block the layer style override in all buttons.

⚠️ **UPDATE: It's an intended feature of sketch that override options of nested symbols cannot be overwritten by the parental symbol. So there's no way to avoid it. But we should think about changing the initial icon color in basic library to the layer style that's more likely to be used (solo or within symbols).**

**Subtasks**  

// DESIGN
- [x] Create branch in Abstract.
- [x] Decide on whether to change the initial icon color (basic library) or not. TBD: What symbols (like Button Regular, Button Icon…) would that affect?
- [x] Check and fix button overrides both in icon symbols and all (nested) instances.

// QA
- [x] 3rd party design sketch review
- [x] Merge corresponding Abstract branch to master and update Changelog (https://www.notion.so/porscheui/Changelog-3fc7172e41954fbbb037a38578fa7cee)
- [x] Export sketch lib file from Abstract into GitHub
