### ISSUE TITLE
Replace final crest assets and meta icons

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#2490]
Scope
---
As we had some further updates in the crest asset we need to replace the final one in all places of the design system, both for the components as well as for all meta icons and sub-packages.

Out of Scope
---
- No changes to marque in V2/V3

Questions
---
- Is it possible to have a private/hidden branch and release? -> No, we will do an release after 08.06.

Notes  
---
- New assets should not increase in size
- Assets: [crest.zip](https://github.com/porsche-design-system/porsche-design-system/files/11642413/crest.zip)
- mstile-585x270 not needed
- `browserconfig.xml` is not relevant anymore
- Article: https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs
- Article: https://stackoverflow.com/questions/48956465/favicon-standard-2023-svg-ico-png-and-dimensions
- Create PDS release

Acceptance criteria
---
- [x] Crest asset size optimized
- [x] All crest (former marque) assets are replaced in the Design System packages
- [x] GitHub Profile image replaced

Subtasks
---
- [ ] Task

Other
---
- don't forget readme
<img width="468" alt="Bildschirmfoto 2023-04-25 um 13 15 14" src="https://user-images.githubusercontent.com/4380295/234260456-69029919-9add-4d42-9ef1-0a18e3016262.png">
