### ISSUE TITLE
React wrappers: support className and custom properties

### ISSUE THREAD

**Issue by o-hook** [porsche-design-system/porsche-design-system#250]
**Scope**  
To get more flexibility, components should grant custom properties (like custom events, etc.) and be assigned with supporting classes.

**Notes**  
error message:
Error:(72, 14) TS2322: Type ‘{ children: string; color: “porsche-light”; style: { background: string; display: string; }; }’ is not assignable to type ‘IntrinsicAttributes & Pick<IonicReactExternalProps<PText & ReactProps, HTMLPTextElement>, “children” | “className” | “variant” | “align” | “color” | “ellipsis” | “tag”> & RefAttributes<...>’.
 Property ‘style’ does not exist on type ‘IntrinsicAttributes & Pick<IonicReactExternalProps<PText & ReactProps, HTMLPTextElement>, “children” | “className” | “variant” | “align” | “color” | “ellipsis” | “tag”> & RefAttributes<...>’.

- Components should support  `... rest` operators
- Modifications of components should be limited to functional/logic not to styling
- Link to Stzencil discussion on Slack: https://ioniccustomersuccess.slack.com/archives/GL2Q8P9T7/p1570439852008800
- Link to Ionic React solution: https://github.com/ionic-team/ionic/blob/master/packages/react/src/components/IonicReactProps.ts

**Subtasks**  
- [x] Discuss requirement with Stencil
- [x] Add support of react specific `className` property to support custom class names
- [x] Add support for custom properties => custom React properties could be included into the React bindings package on demand by the Stencil team.
- [ ] Wait for Stencil to fix TS bug with custom properties (like `style`) since v1.5.0

**QA Notes:**
- [ ] Create test for if `...rest` is supported in React
