### ISSUE TITLE
Web Components support SSR (Wait for Stencil 1.9.)

### ISSUE THREAD

**Issue by o-hook** [porsche-design-system/porsche-design-system#256]
**Scope**  
Check if components still render and are functional if they are prerendered on the server side. Also validate usages of the most common SSR frameworks like Gatsby.

**Note**
This functionality is fundamental to use our components in the Finder, Home&Nav and .Com Teams!

There is an official docs page related to this topic: https://stenciljs.com/docs/prerendering => prerendering seems to work (but only in a Stencil environment?)!

UPDATE: In the next release of Stencil (1.9.x) they have implemented a fix for the `window` issue in SSR applications:
https://github.com/ionic-team/stencil/blob/master/CHANGELOG.md

**Ressources**
- https://www.duetds.com/using-components/#usage-with-react
- https://vaadin.com/forum/thread/17805764/using-vaadin-webcomponents-in-gatsby
- https://whoisryosuke.com/blog/2019/automatic-web-component-docs-using-gatsby-stencil/

**Findings**
- Works with latest Stencil (1.9.0 and maybe lower) and React wrappers like described here: https://www.duetds.com/using-components/#usage-with-gatsby
- Works with native Web Component implementation (no React Wrappers).
- Doesn't support real SSR (components are  still loaded by the Browser)

**Test project Repo**: https://github.com/porscheui/stencil-gatsby-testproject

**Subtasks**  
- [x] Check prerendering support with StencilJS
- [x] Open Ticket in Ionic ZenDesk to discuss SSR with Stencil
- [x] Work on a solution to support Gatsby
- [x] Clarify SSR with XPS team (Sascha Kreher)
- [x] Clarify how to support prerendering on component base and how to implement it in current code base.
- [x] Clarify with finder which solutions should be supported: Gatsby
- [x] Add new test project with Gatsby and Porsche Web Components for Stencil Support.
- [x] Test if latest Version of Stencil (Pre-Release of 1.9.0-12) and DS Plugin (0.0.3) fix this issue.
- [x] Clarify with stencil when 1.9 release is ready to update dependency and include SSR support
