### ISSUE TITLE
Extend Porsche UI Kit App Storefront Sidebar for Component Pages

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#257]
**Scope**  
The Porsche UI Kit App wants to publish component specific design docus in the storefront similar to the Porsche UI Kit Web. Currently the sidebar nav is generated by the config.ts but it is not possible to add seperating headlines, e.g. for Components

**Out of Scope**  
Automatic component page with code and props for App UI Kit

**Notes**  
![image](https://user-images.githubusercontent.com/42934679/64169412-149b3e00-ce4e-11e9-8688-83583aafc19b.png)

**Subtasks**  
// DEV
- [x] Integrate possibility to add component docu pages and seperate them in navigation
- [x] Onboarding of App UI Kit Team

// QA
- [x] 3rd party code review

// QA Notes:
- [x] Test automation for router is missing
- [x] Why is new complexity with a duplicated story view introduced? Either story view should be made more flexible and be abstracted or App team needs to stick with features of Web DS
