### ISSUE TITLE
Pagination (react)

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#26]
**Scope**  
Transfer UI Kit Core Pagination to a full functional React Component in UI Kit React.

**Out of Scope**  
Icon of Pagination Component is still developed with an icon font until UI Kit Core Component has been updated to SVG icon.

**Subtasks**  
Add all related subtasks to be completed in order to finish the issue.
- [x] Finish my changes
- [x] Push my commits to GitHub
- [x] Create samples of all possible states and variants
- [x] Create Unit test
- [x] Test code visual and functional for optimized viewports (only one browser): 320px, 375px, 480px, 768px, 1024px, 1366px, 1920px
- [x] Test code visual and functional for all supported browsers in viewports: 320px, 480px, 760px, 1000px, 1300px, 1760px, 1920px
