### ISSUE TITLE
Approve Abstract by Porsche IT Security

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#262]
**Scope**  
Perform SDE process with Porsche IT security for Abstract

**Subtasks**  
- [x] Initiate SDE appointment
- [x] Provide relevant information for SDE checklist / approval
- [ ] Clear checklist with Abstract
- [ ] Organize and perform penetration test
- [ ] Clear data privacy relevance / confirmation
