### ISSUE TITLE
Integrate Porsche UI Kit with Porsche IT Tools

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#263]
**Scope**  
Initiate the integration of the Porsche UI Kit into the Porsche IT Tools framework (FI) including security approval.

**Notes**  
- Porsche IT Tools (PITT) uses Bitbucket, jFrog and PPN certificates for authentification
- PPN certificates are generated manually based on manual request (no solution for Porsche UI Kit authentification)
- Quickwin: technical user for Porsche Highway to access PorscheUI jFrog
- Discuss possibility of making the Porsche UI Kit Open Source (no auth)

**Subtasks**  
- [x] First discussion/appointment with FI for general understanding and strategy setting
- [x] Appointment with Open Source Office
- [x] Decide on short term actions and long term integration/migration strategy: Routing
- [x] Request email of Highway to create technical user
- [x] Create technical user (analog my porsche) and provide to highway admins
- [x] Wait for highway to create remote repository

// QA
- [x] Test access with Porsche Drive (Sarah Kron)
