### ISSUE TITLE
Colors / Add external brand colors

### ISSUE THREAD

**Issue by annakrohmer** [porsche-design-system/porsche-design-system#265]
**Scope**
In order to enable users to create a google button we should integrate the google brand color in the external color set.

**Notes**  
- Color HEX code: #4285F4 (see https://developers.google.com/identity/branding-guidelines)
- Abstract Link: https://share.goabstract.com/95c16b8b-2f53-41c2-94dd-a31a87e9adf7

**Subtasks**  
// DESIGN
- [x] Add google color to external brand color set (layer styles)
- [x] Re-name "external colors" to "x- external colors" in order to place it beneath porsche color styles
- [x] Create branch in Abstract according to issue number, update sketch library and add collection link to issue

// DEV
- [x] Add relevant SCSS vars according to Abstract 
- [x] Add documentation to existing color docs (https://ui.porsche.com/latest/#/web/scss-utils/variables)

// QA
- [x] 3rd party design sketch review
- [x] 3rd party code review
- [x] 3rd party code docu review
- [x] Code docu review by design 
- [x] Merge corresponding Abstract branch to master
- [x] Export sketch lib file from Abstract into GitHub

// Notes
- [x] Should grey-1 to -8 be shown as SCSS variables at all? Instead grey-light, -lighter, -lightest-on-dark could be used.
