### ISSUE TITLE
Optimize component rendering and FOUC

### ISSUE THREAD

**Issue by o-hook** [porsche-design-system/porsche-design-system#270]
**Scope**  
Until Web Components are registered, the component itself and all child elements are not styled which causes an unwanted "Flash Of Unstyled Content". Before an element is upgraded you can target it in CSS using the :defined pseudo-class. This is useful for pre-styling a component. For example, you may wish to prevent layout or other visual FOUC by hiding undefined components and fading them in when they become defined.

**Notes**  
See officials docs from Google: https://developers.google.com/web/fundamentals/web-components/customelements#prestyle

Also see related Stencil issue: https://github.com/ionic-team/stencil/issues/2101

**Subtasks**  
- [ ] Define global(?) pre-styling mechanism
- [ ] Add pre-styles to global UI-Kit CSS (automatically during build?)

- [ ] Add feature that it's possible to define a set of custom elements which will be loaded independently if they are really used on the page. While loading visibility of any custom elements is hidden. After fully loading those elements and additionally the ones that are used on the page show all of them plus trigger an fully loaded event. (Feature request to Stencil JS)
