### ISSUE TITLE
Create and implement technical user for Browserstack Account

### ISSUE THREAD

**Issue by o-hook** [porsche-design-system/porsche-design-system#274]
**Scope**  
To make our cross browser testing package work, we use my Browserstack credentials as a secret GitHub key. We need to add a technical user and use these credentials instead. 

**Notes**  
- Browserstack 
Account: porsche-ui-kit@porsche.de
Initial Passwort: Porsche1!

**Subtasks**  
- [x] Order 1 user for BrowserStack
- [x] Adjust Browserstack account credentials and store to keypass repo
- [x] Create technical user in Browserstack to use Screenshot API 
- [x] Delete GitHub secrets with old Browserstack credentials and add new ones with the same name for the technical user.
