### ISSUE TITLE
Setup GitHub Actions for 1.0 GH Pages Deployment

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#28]
**Scope**  
Setup the Deployment of the Porsche UI Kit 1.0 to GitHub pages triggered by pushing to master branch `v1`

**Out of Scope**  
Porsche UI Kit 0.x with CircleCI (https://github.com/porscheui/porsche-ui-kit/issues/15)

**Notes**  
- Use GitHub Actions in Porsche UI organization
- Masters are released with an automated version incrementation in the URL ``v1``, e.g.
https://porscheui.github.io/porsche-ui-kit/v1/
- Automated deployment of the 3 sketch libraries (porsche-ui-kit-basic.xml, porsche-ui-kit-web.xml, porsche-ui-kit-prep.xml) with an automated version incrementation in the URL ``v1``

**Subtasks**  
- [x]  Setup docker solution from Portal Services
- [x]  Setup automated deployment of master and branches for 1.x to GitHub Page with Github Actions
- [x]  Test automated deployment pipeline
