### ISSUE TITLE
Extract global types for color and text variants

### ISSUE THREAD

**Issue by o-hook** [porsche-design-system/porsche-design-system#285]
**Scope**  
To handle global type definitions, extract global types to a specific types.ts file

**Subtasks**  
- [x] Extract text color as global type definitions because they are used in many components
- [x] Extract text variants as global type definitions because they are used in many components
- [x] Evaluate of extracting all color variants from color component as global type definitions because they are used in many components

**QA**
- [x] 3rd party code review
