### ISSUE TITLE
[REFACTOR] - Form Fields

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#2893]
### Open Tasks

- [ ] Align the Dropdown of Select Wrapper and Multi Select (#2776)
  - At least re-use styles
  - Abstract a functional component
- [ ] Filter for Select-Wrapper and Multi-Select has white background which should be transparent (#2776)
- [ ] Behaviour to investigate for Multi Select:
  - Named slot needs to be placed before closing root element, otherwise slot change listener might not always work for unknown reasons
  - In case, sr-only text is not placed before `.wrapper` div then the clear button is not able to focus the input for unknown reasons
- [ ] PIN code, label does not forward focus when some value already entered (also didn’t work in the past) (#2891)
- [ ] `label:hover ~ form field` issue with stucked coloring seams to be the case for text-field, textarea and select-wrapper too. Same transition reset for Chrome needs to applied.
- [ ] Pin Code input width should be fully fluid and adjust automatically between a min and max range with CSS only
- [ ] Custom Select-Wrapper Dropdown shall be opened natively with a `for`/`id` relation like it's the case with Multi-Select
- [ ] Select Wrapper should open with custom select dropdown on mobile devices
- [ ] A lot of TODO’s/further improvements commented in form field component styles

### Issues to be created
- [ ] [Bug] Currently non-unique ID’s causing browser errors/warnings
- [ ] Next evolution: Create Form Components without Slot and Re-Use refactored styles 100%

### Issues which needs further discussion
- [ ] Padding of TextField and Textarea when used with counter might not be correct on initial load, another layout solution would be necessary to get it work without the need of JS calculations
- [ ] It seams to be possible to change checked state for radio-button-wrapper while in loading state which can’t be prevented, but loading + checked state should color the input with disabled color
- [ ] We could try using "conditional" css variables (https://stackoverflow.com/questions/52616972/conditional-styles-with-css-custom-properties) to improve SSR support for form fields nested within fieldset.
