### ISSUE TITLE
Reenable automatic generation of ui-kit-wrapper.component.ts  for angular wrapper

### ISSUE THREAD

**Issue by cstickel** [porsche-design-system/porsche-design-system#303]
**Scope**
Remove manual workaround after stencil is fixed

Initial problem: In angular wrapper, If we bundle a lib with the wrappers and then include that library in an angular application compiled with aot and buildOptimizer. Then the buildOptimizer will remove the proxyInputs, etc logic since it's not really part of component. It just thinks it's unused code and tries to make the bundle as small as possible

Check #300 
https://github.com/porscheui/porsche-ui-kit/blob/77959d3863a6baddcf28c8820c1a539a4d39245c/packages/ui-kit-js/stencil.config.ts#L32

stencil bugfix required:
https://ioniccustomersuccess.slack.com/archives/GL2Q8P9T7/p1571060767006100

**Solution**
export function ProxyInputs(inputs: string[]) {
  const decorator = function <T extends {new(...args:any[])}>(constructor:T) {
    const Prototype = constructor.prototype;
    inputs.forEach((item) => {
      Object.defineProperty(Prototype, item, {
        get() { return this.el[item]; },
        set(val: any) { this.el[item] = val; },
      });
    });
    return constructor;
  };
  return decorator;
}

**Tasks**
- [ ] Open Pullrequest in Stencil Repo
- [ ] Update stencil release
- [ ] Remove workaround after new stencil release
