### ISSUE TITLE
Prep / Block Lists

### ISSUE THREAD

**Issue by oliviapala** [porsche-design-system/porsche-design-system#31]
*** Wird noch ausgefüllt ***

**Scope**  
Describe clearly the scope of the change. If possible use the format of a user story.  
AS _Role_  
I WANT TO _outcome_  
SO THAT I _value_  

**Out of Scope**  
- List topics that are not part of this issue to be worked on.

**Notes**  
Share any further information that is relevant for processing.

**Props** (if relevant)  
- Name: e.g. Button Square
- States: e.g. default, hover, focus, active, disabled, loading
- Variants: e.g. filled, ghost
- Cases/Templates: e.g. row
- Themes: e.g. standard + inverted

**Subtasks**  
- [ ] Create UI decision proposal based on research and testing
- [ ] Definition of hierarchy structure and naming of all related states and variants in design and code
- [ ] UI definition approved
- [ ] Create/update Sketch library symbol 
- [ ] Sync Sketch library and guideline pictures to InVision Project
- [ ] Create UI/UX guidelines as .md and include corresponding guideline pictures from Invision
- [ ] Create/update related styles (CSS) and component (JS)
- [ ] Create samples of all possible states and variants
- [ ] Create Code/Implementation guidelines as .md for corresponding component code
- [ ] Create VRT and Unit test
- [ ] Test code visual and functional for optimized viewports (only one browser): 320px, 375px, 480px, 768px, 1024px, 1366px, 1920px
- [ ] Test code visual and functional for all supported browsers in viewports: 320px, 480px, 760px, 1000px, 1300px, 1760px, 1920px
