### ISSUE TITLE
Component / Buttons: Disabled and Loading State

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#324]
**Description**  
The disabled and loading state of the Button Regular / Button Small / Button Icon is not coded according to the design specification
 
**Expected behavior**  
Code according to design specification
https://share.goabstract.com/2c2b81bc-7cd2-457d-beed-1837114ce942

Change Code Examples Label of Buttons into "Some label"
![image](https://user-images.githubusercontent.com/42934679/67680976-af1a8800-f98c-11e9-8b5b-b31dd9b18511.png)

**Screenshots**  
![image](https://user-images.githubusercontent.com/42934679/67680608-d91f7a80-f98b-11e9-83c7-caa001c0df38.png)

**Tasks**
- [x] Update Disabled and Loading State for Button Regular/Small
- [x] Update Disabled and Loading State for Button Icon
- [x] Update Docu Example of Button Regular/Icon
- [x] Update vrt fixtures
- [x] Rewrite Component Labeling of Buttons into "Some label"
