### ISSUE TITLE
Create Component / Button Regular

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#33]
**Scope**  
- Move the final Button Component from Porsche UI Kit react to Porsche UI Kit 1.0 with the final source structure including the source setup and linking of relevant mixins/styles/variables for Buttons.
- Refactor Button Component in Sketch library due to updated layer and text styles.
- Visualize as compiled .mdx pages, both for the design guideline and for the code samples and guidelines, including all consumer relevant information.

**Abstract collection link** 
https://share.goabstract.com/a024ddc9-d32f-4c4a-aff6-b387ee5df67f

**Link to documentation**
https://www.notion.so/porscheui/Button-Regular-6361662495a942b78eb1e5470996db5b

**Notes** 
- After moving React component to Porsche UI Kit 1.0 it should be validated
- SRC Button includes SCSS, TSX, VRT, SpecMDX for visual testing
- Button docu: #204 

**Subtasks**  

// DESIGN:
- [x] Validate Spacing/Density System for Buttons to ensure consistency and accordance to docu
- [x] Sketch refactoring: Adaption of new layer/text styles, spacings and icons
- [x] Sketch structure: Check override options (integrate emojis, check wording etc.)
- [x] Check focus state: Adapt border in new focus color instead of hover state?
- [x] Review & optimize UI/UX guidelines, remove all sales-related parts (blue buttons)
- [x] Create must-have design docu (optionally create and upload assets)
- [x] Replace code examples in design docu by corresponding component

// DEV:
- [x] Transfer dependent loader component
- [x] Setup source structure of Button Component and related styles/configurations in Porsche UI Kit 1.0
- [x] Move and validate Button 1.0 from Porsche UI Kit react
- [x] Refactor buttons to new color definitions 
- [x] Create dev docu .mdx(s)
- [x] Refactor buttons in code (add spacing 4px between icon and text, left-padding 11px instead of 15px)
- [x] Refactor to web component
- [x] Create and perform VRT test
- [x] Release Web library (replace .sketch file on server from Abstract export)
- [x] Test code visual and functional for optimized viewports (only one browser): 320px, 375px, 480px, 768px, 1024px, 1366px, 1920px
- [x] Test code visual and functional for all supported browsers in viewports: 320px, 480px, 760px, 1000px, 1300px, 1760px, 1920px

// QA
- [x] 3rd party design sketch review
- [x] 3rd party design docu review
- [x] 3rd party code review
- [x] 3rd party code docu review
- [x] Code docu review by design 
- [x] Merge corresponding Abstract branch to master 
- [x] Export sketch lib file for deployment
