### ISSUE TITLE
Extend Component Meta

### ISSUE THREAD

**Issue by henrijoss** [porsche-design-system/porsche-design-system#3366]
Scope
---
In preparation of a component configurator on the storefront, we need to add additional information to `componentMeta`.

Add SlotMeta
- `description`
- Prop relationship e.g. `heading`

PropMeta:
- `isControlled` indicates this prop value likely will be managed in an external state variable and changed dynmically from outside
- `mutable` indicates this prop is mutated from within the component

Improved SlotMeta:
```
type SlotMeta = {
  name: string; // Name of the slot. Empty name corresponds to the default slot.
  description: string;
  isRequired?: boolean; // Specifies if the slot is required. If undefined the slot is not required.
  allowedTagNames?: (TagName & HTMLElement)[]; // Specifies which tagNames are allowed to be used. If undefined all tags are allowed.
  hasAltProp?: boolean; // Specifies if the slot has an equal name prop which can be used instead.
};
```

ControlledStateMeta:
```
/**
 * Describes a property whose state is likely to be externally controlled and updated via a specific event.
 */
type ControlledStateMeta = {
  prop: string;
  event: string;
};
```

Related issues:
[#3315](https://github.com/porsche-design-system/porsche-design-system/issues/3315)

Out of Scope
---
List topics that are not part of this task.

Notes  
---
- Can we use Stencil Docs generation instead of our own logic? https://stenciljs.com/docs/docs-custom

Acceptance criteria
---
- [ ] Criteria

Subtasks
---
- [ ] Add `@slot` documentation
- [ ] Add `@controlled` documentation
- [ ] Add `@prop` documentation (CSS Custom Properties)
- [ ] Replace `component-meta` with https://stenciljs.com/docs/docs-custom
- [ ] Improve slot meta data structure 
- [ ] Add controlled state meta
- [ ] Add CSS Custom Properties
- [ ] Adjust usages
- [ ] Test to assure slot and controlled docs are in sync with component code?
