### ISSUE TITLE
Sketch Dependencies

### ISSUE THREAD

**Issue by kkohli-bg** [porsche-design-system/porsche-design-system#343]
**Acceptance Criteria**
Sketch: No dependencies (plugins...)

**Subtasks**
- [x] Abhängigkeit Icon font? - Entscheidung 06.11
- [x] Smart Layout statt Anima
- [x] Anpassung Doku in Storefront PR #397 
- [x] finale QA
- [x] Merge Sketch Library und neuer PR mit Master Export
- [x] Neue Library release
- [x] Info an Community

**Size**: 1
