### ISSUE TITLE
Focus State

### ISSUE THREAD

**Issue by kkohli-bg** [porsche-design-system/porsche-design-system#345]
**Acceptance Criteria**

**Notes**

Wir verwenden bei jeder Komponente eine durchgängige Border in der Stärke von 2 px in der Fokusfarbe. Jede Komponente wird trotz alle dem individuell betrachtet und erhält bei Bedarf eine weitere inline Border in weiß (auf dark). Beispiel: Button

**Subtasks**
- [x] Entscheidung über Aussehen des Focus State: 07.11. (https://www.notion.so/porscheui/Notes-TBD-39fc288a09794cebb1e2790a36b842ed)
- [x] Anpassung / Ergänzung Layer Style in der Basic
- [x] Anpassung States in Sketch (Artboard)
- [x] Anpassung der Doku in Storefront
- [x] QA

**Size**: 3
