### ISSUE TITLE
Reduced Font Sizes

### ISSUE THREAD

**Issue by kkohli-bg** [porsche-design-system/porsche-design-system#349]
**Acceptance Criteria**
Reduced Font Sizes in Sketch Library

**Scope**
- Closes #290 

**Subtasks**
- [x] Entscheidung über finales Set bis 12.11:

Copytext:
• text-12 wird text-x-small
• text-16 wird text-small

Additional sizes:
• text-24 wird text-medium
• text-36 wird text-large
• text-52 wird text-x-large

Headlines wie gehabt

- [x] Ein- / Umbau font styles in Basic Library (optisch + strukturell)
- [x] Anpassung Docu (Image) in der Storefront 
- [x] Anpassung Docu (Text) in der Storefront 
- [x] QA (MB)
- [x] QA (Anna)

**Size**: 2
