### ISSUE TITLE
Final V1 Check

### ISSUE THREAD

**Issue by kkohli-bg** [porsche-design-system/porsche-design-system#351]
**Acceptance Criteria**
Recheck aller Komponenten und Guidelines.

**Subtasks**

**Sketch Libraries**

- [x] Mergen aller Abstract-Branches in Master für Basic & Web Library (Final Check muss auf finaler Export-Datei im Master stattfinden; falls hier noch etwas korrigiert werden muss, muss Branch #351 geöffnet werden)
- [x] Title auf Symbol Page prüfen (inkl. Überlagerung der Symbole auf der Symbol Page)
- [x] GitHub Branch 351 erstellen
- [x] Basic: Prüfung aller Komponenten & Styles in Sketch aus UI Kit - (Anzahl, Funktionalität, Namings, Hierarchien, Größen, Verknüpfung/Nesting) → https://www.notion.so/porscheui/5-Symbol-QA-6bfc9c1683354703a465abf2231da79a
- [x] Basic: Prüfung alles Komponenten & Styles in Sketch aus Konsumentensicht  in der Library (Einsatz testen, Adaption, Manipulation, Replacement & Overrides) → https://www.notion.so/porscheui/5-Symbol-QA-6bfc9c1683354703a465abf2231da79a
- [x] Web: Prüfung alles Komponenten & Styles in Sketch aus Konsumentensicht in der Library (Einsatz testen, Adaption, Manipulation, Replacement & Overrides) → https://www.notion.so/porscheui/5-Symbol-QA-6bfc9c1683354703a465abf2231da79a
- [x] Web: Prüfung aller Komponenten & Styles in Sketch aus UI Kit -  (Anzahl, Funktionalität, Namings, Hierarchien, Größen, Verknüpfung/Nesting) → https://www.notion.so/porscheui/5-Symbol-QA-6bfc9c1683354703a465abf2231da79a
- [x] Export und Upload Sketch Files in GitHub Branch
- [x] PR erstellen 
- [x] Merge in GitHub Master = Release!

**Checken aller Storefront-Texte**
- [x] Verknüpfungen checken (Icons)
- [x] Visueller Check (einheitliche Darstellung Content etc.)
- [x] Color Namings in der kompletten Doku korrigieren und an das neue Naming anpassen
- [x] Verknüpfungen checken (Bilder, Links)
- [x] Finales Korrekturlesen aller Storefront-Texte Inhalt, Orthografie, Schlüssigkeit, Übereinstimmung mit Libraries sowie Dev.
- [x] Naming von Porsche UI-Kit in Porsche Design system checken

**Review Code-Umsetzung**
- [x] Finaler Check (Abgleich Sketch ↔︎ Code)

**Release Notes**
- [x] Eintrag in Changelog

**Size**: 13
