### ISSUE TITLE
Exchange new designed icon assets

### ISSUE THREAD

**Issue by kkohli-bg** [porsche-design-system/porsche-design-system#352]
**Scope**
Redraw all icons of the 1.0 set according to the defined icon style guide and replace the assets on the CDN.

**Note**
- No removal, adding or renaming of icons

**Subtasks**
- [ ] Redesign all 1.0 icons
- [ ] Export SVGs and minify
- [ ] Update meta data
- [ ] Upload new SVGs and meta data to CDN
