### ISSUE TITLE
Definition of Release Strategy

### ISSUE THREAD

**Issue by kkohli-bg** [porsche-design-system/porsche-design-system#353]
**Notes**
Define release strategy and add to public docu

**Notion**
https://www.notion.so/porscheui/Release-Management-d928bc0ded9d4cd9ae39b9099581f717

**Subtasks**
- [x] Definition Release Strategie (Zyklen/Zeiten)
- [x] Add Maintenance window, release cycle to docu
- [x] Finalisierung V1 major / minor / patch definition (insb. Design Review)
- [x] Dokumentation Release Abhängigkeiten Design <-> Dev

**Size**: 13
