### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by kkohli-bg** [porsche-design-system/porsche-design-system#357]
**Acceptance Criteria**

**Scope**
- Closes Branch #290 

**Subtasks**
- [x] Refine Interface
- [x] Define new set of variants
- [x] Add inherit mode
- [x] Optional: BP-Support
- [x] Update docs
- [x] QA

**Size**: 3
