### ISSUE TITLE
Release preparation

### ISSUE THREAD

**Issue by kkohli-bg** [porsche-design-system/porsche-design-system#373]
**Acceptance Criteria**

**Subtasks**
- [x] Communication 1.0 RC preparation

**CODE**
- [x] NPM dependency update
- [x] Merge all 1.0 related Branches into Master and export Sketch libs
- [x] Change notification bar from red to green and adjust text
- [x] Update Version number in storefront
- [x] Deactivate automatic deployment of master branch and icon workflow
- [x] Optional: Update Storefront changelog
- ~Optional: Optimize package.json~ #444

**Size:** 13
