### ISSUE TITLE
Link Pure

### ISSUE THREAD

**Issue by o-hook** [porsche-design-system/porsche-design-system#391]
**SCOPE**
Basic link component based on Text Link Icon.

**OUT OF SCOPE**  
- Disabled- / loading state

**CODE (Size 20)**
- [x] Variants: text-icon (default) / icon only
- [x] Sizes: BPC (based on pre defined global text sizes defined in #349 ) + inherit
- [x] Add event handling
- [x] Add router support
- [x] Add focus state
- [x] Update docs

**DESIGN (Size 5)**
- [x] Hierarchie in Sketch ändern = von Action zu Navigation
- [x] States (Default, Hover/Active, Focus)
- [x] Focus State adaptieren (Border mit 1px Abstand)
- [x] In definierten Textgrößen anlegen (siehe #349)
- [x] Anpassung in Notion (Structure)
- [x] Anpassung Artboards in Sketch
- [x] Icon only Variante analog der definierten Größen
- [x] Anpassung Images für die Storefront
- [x] Anpassung Doku in Storefront (auf GitHub Branch #392)
- [x] QA (Sketch)
- [x] QA (Docu)
