### ISSUE TITLE
Button Pure

### ISSUE THREAD

**Issue by o-hook** [porsche-design-system/porsche-design-system#392]
**SCOPE**
Basic button component based on Text Link Icon.

**CODE (Size 8)**
- [x] Variants: text-icon (default) / icon only
- [x] Sizes: BPC (based on pre defined global text sizes defined in #349 ) + inherit
- [x] Add event handling
- [x] Add focus state
- [x] Update docs

**DESIGN (Size 5)**
- [x] Naming definieren
- [x] States (Default, Hover/Active, Disabled, Loading, Focus)
- [x] Focus State adaptieren (Border mit 1px Abstand)
- [x] In definierten Textgrößen anlegen (siehe #349)
- [x] Icon only Variante analog den der definierten Größen
- [x] Anpassung in Notion (Structure)
- [x] Anpassung Artboards in Sketch
- [x] Anpassung Images für die Storefront
-  [x] Anpassung Doku in Storefront (auf GitHub Branch #392)
- [x] QA (Sketch)
- [x] QA (Storefront)
