### ISSUE TITLE
Move Confluence Docu to GitHub

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#4]
**Scope**  
Research all documentation regarding Porsche UI Kit which is relevant for a _Consumer_ and add it to Pattern Lab as new page. Research all documentation regarding Porsche UI Kit which is relevant for a _Contributor_ and add it to GitHub Wiki. To remove Confluence from the Techstack of Porsche UI

**Notes**  
If possible use .md instead of .hbs for creating the documentation in Pattern Lab

**Subtasks**  
Add all related subtasks to be completed in order to finish the issue.
- [x] Create .md Files within the GitHub Wiki for _Consumers_
- [x] Move .md Files to Repository
- [x] Deploy .md Files to GitHub Pages
