### ISSUE TITLE
Prep / Remove unsed icons

### ISSUE THREAD

**Issue by oliviapala** [porsche-design-system/porsche-design-system#41]
**Scope**
Delete unused icons.
Only the icons that are in use remain in the library.
So that we have a clean library for the current version.

**Out of Scope**

* Icons are created on demand - as we get new icons from Strichpunkt
Icons are created in 24 x 24

**Notes**
The icons should be reduced to the minimum necessary and there should be no duplications.

**Props** (if relevant)

* Name: Icons in use 
* States: default
* Themes: standard

**Subtasks**

* [ ] Create UI decision proposal based on research and testing
* [ ] Definition of hierarchy structure and naming of all related states and variants in design and code
* [ ] UI definition approved
* [ ] Create/update Sketch library symbol
* [ ] Sync Sketch library and guideline pictures to InVision Project
* [ ] Create UI/UX guidelines as .md and include corresponding guideline pictures from Invision
* [ ] Create/update related styles (CSS) and component (JS)
* [ ] Create samples of all possible states and variants
* [ ] Create Code/Implementation guidelines as .md for corresponding component code
