### ISSUE TITLE
Create Component / Button React

### ISSUE THREAD

**Issue by o-hook** [porsche-design-system/porsche-design-system#44]
**Scope**  
Transfer styling and button types to UI Kit React and adapt existing button component
AS _User_  
I WANT TO _have the same button look & feel_  
SO THAT I _have always the same online experience across Porsche_  

**Out of Scope**  
- Implement SVG icons in Button Component

**Props** (if relevant)  
- Name: Button Regular
- States: default, hover, focus, active, disabled, loading
- Variants: filled, ghost, group
- Themes: standard + inverted

**Subtasks**  
- [x] Create/update related styles (CSS) and component (JS)
- [x] Create samples of all possible states and variants
- [x] Create Code/Implementation guidelines as .md for corresponding component code
- [x] Create Unit test
- [x] Test code visual and functional for optimized viewports (only one browser): 320px, 375px, 480px, 768px, 1024px, 1366px, 1920px
- [x] Test code visual and functional for all supported browsers in viewports: 320px, 480px, 760px, 1000px, 1300px, 1760px, 1920px
