### ISSUE TITLE
Clean-up 1.0.0-RC.1

### ISSUE THREAD

**Issue by oliviapala** [porsche-design-system/porsche-design-system#450]
**Scope**  
Due to alpha release, it's necessary to optimize and clean up multiple things as well as documenting them for future editing. Have a look at the list below.

**Subtasks**  

// GENERAL
- [x] Rename Abstract Project
- [x] Adjust Hex code of the neutral colors in the color doku
- [x] Rename all Masterfiles in Abstract (Basic and Web, **!!! After merge Branch to master !!!**)

// WEB LIBRARY

- [x] Add new Collections
- [x] Open new issue branch in Abstract
- [x] Remove old layer styles from old remote librarys
- [x] Remove old text styles from old remote librarys
- [x] 3rd party design review
- [x] Merge changes to master

// LIBRARY TEMPLATE
- [x] Update Text-Style
