### ISSUE TITLE
Replace Brand Guide content with Design System

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#473]
**Scope**  
The existing [Brand Guide content for digital media](https://brandguide.porsche.com/comm/manual/view/id/1114) is outdated and should be replaced with a link to new Design System content. 

**Notes**
- Link to Brand Guide: https://brandguide.porsche.com/site/login
- Brand Guide changelog: https://www.notion.so/porscheui/Brand-Guide-changes-c8fba47d494242a88b6f91a2fa0027a1
- Brand Guide is maintained by CMS. @marcelbertram is updating the content

**Sources**
- Brand Guide mood image: https://share.goabstract.com/4609d919-f742-449a-b3a1-c75820e27749

**Subtasks**
---
- [x] Update notion changelog to identify update requirements
- [x] Creation of "pattern / elements" mood image (still image from Design System video)
- [x] Replace outdated Brand Guide content with links to Porsche Design System documentations
