### ISSUE TITLE
Design Kit / Outsourcing of basic elements in extra library

### ISSUE THREAD

**Issue by annakrohmer** [porsche-design-system/porsche-design-system#49]
**Scope**  

* Setting up an extra library for basic elements (typography, colors, icons, spacings/grid).
* Deleting the respective elements from Core library and reconnect them to the new basic library whilst making sure that everything is related and nested properly.
* Setting up a proper naming convention for sketch libraries.

**Notes**  

A good naming convention would be:
- **porsche-ui-kit-basic.sketch**
- **porsche-ui-kit-web.sketch (for web components)**
- porsche-ui-kit-web-prep.sketch (for web components)
- porsche-ui-kit-app.sketch (for app components)
etc.

**Subtasks**  

**01 - Library Splitting: web ↔︎ basic (@annakrohmer)**
- [x] Open up a new sketch library document (porsche-ui-kit-basics.sketch) and re-name the old one (porsche-ui-kit-web.sketch)
- [x] Insert all basic elements (typography set, colors, icons, layer styles) into the new library, delete them from porsche-ui-kit-web.sketch. (As for the icons, we still insert only the ones in use and are going to add the rest as soon as the new icon set is available.)
- [x] Testing: Release both basic and web kit on GitHub/RSS (twice, to imitate update) to check if the nesting/reference between the libraries remains. If there are any issues, it might be a knockout criterion for splitting the libraries!

**Clean-up: basic**
- [x] Check symbols: Are all symbols there? Is everything nested/referenced properly?
- [x] Check text styles: Are text styles complete? Do all symbols refer to the correct text styles? 
- [x] Check colors (incl. color picker set): Are all colors there? Do all symbols refer to the right colors?
- [x] Check layer styles: Are layer styles complete? Do all symbols refer to the correct layer styles?
- [x] Check icons: Are they inserted / set up properly?
- [x] Use Symbol Organizer / Symbol Instance Renamer (→ Rename Instances on All Pages (Except Symbols Page)) to clean-up everything.
- [x] 3rd party review
- [x] Merge in Abstract master
- [x] New RSS release of basic library

**Clean-up: web**
- [x] Check symbols: Are all symbols there? Is everything nested/referenced properly?
- [x] Check text styles: Are text styles complete? Do all symbols refer to the correct text styles? 
- [x] Check colors (incl. color picker set): Are all colors there? Do all symbols refer to the right colors?
- [x] Check layer styles: Are layer styles complete? Do all symbols refer to the correct layer styles?
- [x] Check icons: Are they inserted / set up properly?
- [x] Use Symbol Organizer / Symbol Instance Renamer (→ Rename Instances on All Pages (Except Symbols Page)) to clean-up everything.
- [x] 3rd party review
- [x] Merge in Abstract master
- [x] New RSS release of web library

**Documentation**
- [x] Document naming convention of sketch libraries in GitHub Wiki.
