### ISSUE TITLE
Setup SCSS structure in 1.x workshop

### ISSUE THREAD

**Issue by o-hook** [porsche-design-system/porsche-design-system#50]
**Scope**  
Setup basic SCSS structure which encloses variables, mixins, functions, common

**Out of Scope**  
- create/move component scss

**Notes**  
- Compare with UI Kit Core 0.x

**Subtasks**
- [x] Define SCSS base structure in workshop
- [x] Make sure to include finalized structure into 1.x storefront
- [x] Add webfonts to Github pages which servers temporary as CDN until #56 is finished
