### ISSUE TITLE
Stencil bug - support named slotted content nested in a component in IE11 (or no-shadow dom)

### ISSUE THREAD

**Issue by o-hook** [porsche-design-system/porsche-design-system#502]
**Description**  
Actually we assume that Stencil does not support nesting a slot directly inside a component when shadow DOM is disabled (e.g. IE11). You must wrap the slot with an extra HTML tag.

**Example**  
```
 return (
      <Host>
          <p-text>
            <span> { /* is needed to forward named slot to default slot in Stencil JS */}
              <slot name='label'/>
            </span>
          </p-text>
      </Host>
    );
```

**To Reproduce**  
```
 Clone Testproject GitHub Repo: git@github.com:porscheui/stencil-bugfix-project.git
```

**Expected behavior**  
It should be possible to include named slots directly inside a component without an extra wrapping div.

**Current berhaviour**
In the test project, Stencil renders the examples just fine, but in our p-text-field component we need a wrapping element.

**Notes**
- Issue is opened on Stencil Repo: https://github.com/ionic-team/stencil/issues/2188
- Repsonse from Srencil: https://ionic.zendesk.com/hc/en-us/requests/28353
This issue won't be fixed.

** Subtasks**
- [x] Setup test project to reflect this bug
- [x] Open corresponding Zendesk ticket
- [x] Wait for STencil responds....
