### ISSUE TITLE
Create Typography Prototype and perform Tests

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#51]
**Scope**  
Create testable prototypes for 4 the different typography style definitions using major application sites:
- https://finder.porsche.com/de/de_DE/search/list
- https://www.porsche.com/germany/models/911/911-carrera-models/carrera-s/
- https://connect-portal.porsche.com/core/de/de_DE/home
- https://www.porsche.com/germany/modelstart/all/?modelrange=911

**Notes**  
Try to export sites as full responsive prototype and override typo classes
- Display Resolutions for Screens: 320px, 375px, 480px, 768px, 1024px, 1366px, 1920px

**Subtasks**  
- [x] Provide mapping table for font-sizes and line-heights @annakrohmer 
- [x] Create Sites with new Typo Variants and render Screens for relevant display resolutions
- [x] Setup aesthetic and functional tests for different variants
- [x] Recruit testers and perform test
- [x] Document test results in Porsche Drive
