### ISSUE TITLE
Check font style alignment

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#512]
**Scope**
It seems different metrics of the font faces cause a wrong vertical alignment in our elements.

![image (7)](https://user-images.githubusercontent.com/42934679/74325550-1a943400-4d89-11ea-96e5-b1345d9db117.png)

**Sub-tasks**
- [x] Analyse current behavior and font assets
- [x] Clearify with typetailors
- [x] Modify font if required
