### ISSUE TITLE
Icon Refinement v1.1

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#516]
**Scope**  
The current icon set developed in Dec/Jan has been optimized for 48x48 px and is located in the central [Porsche Icon library](https://share.goabstract.com/a9887464-0a5e-40fb-9bbf-ca2b8d792c42?sha=423ece83b10e1c575c800ad75d0e665cf9dfc80e).
For web purpose the icons have been transferred to the [Basic Library](https://share.goabstract.com/755c6b8f-2287-4a1d-b10a-196e167f6391?sha=ea1cdbbd42a9b07849d82857f0d3178a5b888cd2) and seamlessly scaled to 24x24 px without any further optimization.

According to community feedback the scaled 24x24 px icons result in optical issues (blurry optic) and some minor visual inconsistencies have been detected (too much white space, inhomogeneous proportional icon sizes).

**As 24x24 px is the most common use in web applications (approx. 90%), we should optimize the Porsche icon set for this size (instead of 48x48 px).**

**Notes**  
- Important: Icons are being built in Adobe Illustrator due to refined construction possibilities and more detailed export options. Afterwards they are transferred to Sketch library. 
- Test file (optimization in Sketch quick & dirty and by eye): https://share.goabstract.com/ea75edac-5606-4c7a-9217-3887a277d3af?sha=58b2d76a8e1c830efcbe3bad0b472eaa02fb9ca3

**Optimization steps**
1. Adapt [icon basic file](https://www.notion.so/porscheui/Template-ffe5b7341667415389c5df6d5e7a707d#09939bcea180414891b1679f2b36282d) (.ai) to 24x24 px, incl. base areas (squares, rectangles etc.)
2. Optimize:
- Base squares to less white space (important: in comparison to text in copy size!)
- Stroke width 
- Use even pixel values whenever possible to enable centered positioning and smooth resizing to 48x48 px  
- Optimize icon sizes where needed for a better visual harmony
- Snap strokes to pixel grid as good as possible
- Check crossed lines for angles to optimize sharpness (e.g. 45° instead of 50°), especially for arrows
- Whilst optimizing: Always check in parallel if scaling to 48x48 px works properly.

**Link to resources**
- Abstract icon library (48x48 px): https://share.goabstract.com/a9887464-0a5e-40fb-9bbf-ca2b8d792c42?sha=423ece83b10e1c575c800ad75d0e665cf9dfc80e
- Icons in Abstract basic library (24x24 px): https://share.goabstract.com/755c6b8f-2287-4a1d-b10a-196e167f6391?sha=ea1cdbbd42a9b07849d82857f0d3178a5b888cd2

**Subtasks**
---
**Design**
- [x] Check and update icon template file (.ai) for 24x24 px
- [x] Integrate new .ai template in [notion](https://www.notion.so/porscheui/Template-ffe5b7341667415389c5df6d5e7a707d) 
- [x] Design all icons according to new definitions (.ai, separated by categories)
- [x] 3rd party review
- [x] Integration / replacement of iconset in Basic Library (Light and Dark Theme)
- [x] Export and cleanup SVGs for upload
- [x] Provide production and export files (.ai and .svg) in GitHub repository porsche-icons/icon-production

**Code**
- [x] Update icons
- [x] Create automated icon asset generation and management
