### ISSUE TITLE
Storefront beautification

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#53]
**Scope**  
Finalize the Design for the storefront 1.0 release.

**Out of Scope**  
- Component finalization/creation, i.e. tab nav, accordion except of Porsche UI Kit react components

**Notes**  
- Map/Use stylings and components as other product consumers would; import styles and components where possible) from Porsche UI Kit 1.0 or Porsche UI Kit react 0.x
- UI design file: https://app.goabstract.com/projects/d1ab2250-20af-11e9-a30e-8da092a437ca/branches/87173c91-e10b-49a9-a5ad-6c4dd1101287/collections/818b6281-77bc-4edf-bd0d-a58d72329e20/presentation

**Questions**
- [x] Should we provide versioned documentation? => no
- [x] Should we provide only major versioned documentation? => yes
- [x] Should we provide only latest documentation? => no
- [x] When we provide versioned documentation, should we forward to some sub url "latest" for bookmarking reasons? => yes
- [x] When we provide versioned documentation where should we provide some kind of version switcher and which data is shown in this module? => somwhere on the page, e.g. on history page

**Subtasks**  
- [x] Create base SCSS for all relevant markups and code (Theme) in storefront @Code
- [x] Provide Styled Storefront Design / Layout @Design
- [x] Finish styling of all .mdx contents
- [x] Added feature toggle
- [x] Finish styling of sidebar navigation
- [x] Finish styling of props table
- [x] Finish styling and function of footer
- [x] Refactor sidebar component structure
- [x] Get rid of BEM styling in Storefront components
- [x] Provide rudimental responsiveness for storefront
