### ISSUE TITLE
Spike: Consumer Tracking of PDS components

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#532]
**Scope**  
We want to track which components are being used by which team/product and how many times to get a better sense for the relevance of components and the adoption within the product organisation.

**Note/Finding**
- Preferred **Passive CDN log tracking** with global one time "tracking pixel" for basis tracking of all product team setups
- Referral URL could be sent via ajax request (in case of referrer policy)
- Legal: Is tracking of resource loading critical because no user-interaction tracking, storage of logs?
- Edgecast log: Optimal would be a log API with requests
- We want to track: What team (referrer URL) is using which components in which version (content based hashes)
- Extend later by **Active Google Analytics tracking** support

Subtasks
---
- [x] Evaluate what we want to measure/track
- [x] Evaluate technical solution how to track single components via CDN and/or NPM
- [x] Discuss solutions and create follow-up issue
