### ISSUE TITLE
Define release strategy for 1.0

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#54]
**Scope**  
Decide on the 1.0 release strategy for consumers currently using the Porsche UI Kit 0.x.

**Notes**  
- Both libraries will be possible to use at the same time
- Old library will still be hosted and provided but not maintained
- Switch from soft to hard migration (completely new version); Like AngularJS and Angular

**Subtasks**  
- [ ] Release 1.0
- [ ] Decide on Release Strategy
- [ ] Document Release Strategy decision
- [ ] Define reasons for decision
- [ ] Inform Community about decision
