### ISSUE TITLE
CDN Performance China

### ISSUE THREAD

**Issue by cstickel** [porsche-design-system/porsche-design-system#556]
**Description**  
Portal Core experienced slow CDN performance in China. We need to check our CDN configuration why fonts and icons load slow, since EdgeCast should have fast instances for China.

**Expected behavior**  
Files should be loaded fast from CDN also in China.

**Screenshots**  
![cdn-performance](https://user-images.githubusercontent.com/1065026/76194457-803bda80-61e6-11ea-8bd7-09ee71741bf7.png)

Results after research
---
China permits ICP (licenses) only to chinese companies. As porsche.com is owned by Porsche AG, we are only allowed to host via porsche.cn

We will setup a automated distribution/clone of our CDN including all settings to **cdn.ui.porsche.cn**

We need a solution to configure the CDN path by the product teams according. Existing solutions (My Porsche, Sales, P.COM) should be considered.

**Tasks**
- [x] Get in contact with Edgecast support
- [x] Provide Cert for cdn.ui.porsche.cn with Christian Arrich (UDG)
- [x] Setup cdn.ui.porsche.cn and SSL certificates
- [x] Discuss distribution solution with Verizon
- [x] Implementation of China Cache by Verizon
- [x] Retest loading of assets in China with New Relic
