### ISSUE TITLE
Provide Porsche CDN for global asset delivery

### ISSUE THREAD

**Issue by o-hook** [porsche-design-system/porsche-design-system#56]
**Scope**  
Provide access to a Porsche owned CDN to manage delivery of global assets like webfonts, Porsche crest, icons, etc.

**Notes**  
Access credentials in Porsche UI Keypass
- Implement in V0 https://github.com/porscheui/porsche-ui-contribution/issues/20

**Subtasks**  
- [x] Request test CDN access
- [x] Provide test CDN access
- [x] Test asset management on test CDN
- [x] Request production CDN with own URL (especially for UI Kit product)
- [x] Provide production CDN access
- [x] Define asset structure and versioning
- [x] Add webfonts and Porsche Marque assets
- [x] Provide and upload SSL certificate; https://highway.porsche.com/jira/browse/PCOMSERVOP-32
- [x] Adapt path of webfonts inclusion in workshop setup
- [x] Add separate task to contribution board to update webfont paths in Core and React

// QA
- [x] Browsertesting
- [x] 3rd party code review
- [x] 3rd party code config review
