### ISSUE TITLE
Create tracking pixel

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#625]
**Scope**  
Add a tracking pixel file to design system package and test analytics possibilities with Edgecast that is disabled for caching.

**Notes**
- Add ajax request to loader that loads the CDN tracking file
- Add Design System version to request
- Follow-up of #532 

- Amazon AWS Konto: 5951-0879-5977
https://console.aws.amazon.com/
designsystem@porsche.de

- AWS QuickSight: https://eu-central-1.quicksight.aws.amazon.com/
Account: `porsche-design-system`
Credentials from above.

Subtasks
---

**BUSINESS**
- [x] Clarify tracking logs (API) with Edgecast

**CODE**
- [x] Add tracking file to design system CDN
- [x] Add ajax request to load tracking file
- [x] Activate report builder for verizon
- [x] Setup caching settings for tracking file with Edgecast
- [x] Check raw logs via FTP
- [x] Try out Report Builder: https://docs.whitecdn.com/cdn/re3/index.html#EC360_Analytics_Suite/RB/Report-Builder.htm
- [x] Setup AWS S3 for tracking pixel
- [x] Setup AWS CloudFront (CDN): https://d3nll2jx8s265d.cloudfront.net/collect.gif
- [x] Setup AWS S3 for logs
- [x] Setup AWS Athena to query logs
- [x] Setup AWS QuickSight to visualize Athena
- [x] ~~Deny requests from localhost in CloudFront~~ filter out referrers of localhost and 192.168.*.*
- [x] ~~Prevent logging of ip address~~ anonymize last section of ip address
- [x] Let Ola (?) disable Report Builder and Raw Logs on Verizon CDN
