### ISSUE TITLE
React PIcon component shows wrong icons (sometimes)

### ISSUE THREAD

**Issue by o-hook** [porsche-design-system/porsche-design-system#637]
**Description**  
The Gravity Core Team reported a bug regarding loading the right icons in their React application.

**Bug description:** we observe a strange little issue with components-react v1.3.0 / v.1.4.0-rc: sometimes, the default PIcon is rendered even though the properties define another icon. When the page is refreshed it randomly toggles between the correct and wrong icon. The networking tools show that the correct icon is loaded from the CDN in any case. We haven't been able to reproduce the behavior with v1.2.0.

Bug also seems to occur in Finder team with NextJS.

**Note:** This bug might be in conjunction with Stencil Update to 1.9.x. 

https://porschedev.slack.com/archives/CT7AVHTTQ/p1587375332053700

**To Reproduce**  
Not possible atm. Wait for acces to example project.

**Expected behavior**  
The right icon should be shown.

**Screenshots**  
![image](https://user-images.githubusercontent.com/40788023/79751725-5f04f880-8313-11ea-843e-5003a4af2d6e.png)

**Test Device (please complete the following information):**  
 - Device: Desktop
 - OS: Windows
 - Browser: All Browsers

**Solution**
The Bug occurs because of race conditions while calling icons from cdn. Bug is fixed, we should implement Test for this behavior to make sure it wont happen again.

**Sub-Tasks**
- [x] Try to reproduce this bug in our sample test projects (React and NextJS)
- [x] Implement unit Test to ensure Icon cache is correct
- [x] Implement e2e Test to ensure correct icon loading from cdn
- [x] Unset icon when prop name is changed
- [x] Validate name prop against icon manifest
- [x] Implement unit Test for new buildIconUrl()
- [x] Discuss CI/CD solution for puppeteer e2e testing
- [x] Write Unit Test for every manifest svg icon from cdn
- [x] Single command puppeteer execution
- [x] Define Stencil e2e helper and create own
- [x] Refactor tests to work with new helpers 
- [x] Improve stencil dev-server runtime in CI/CD after e2e usage
