### ISSUE TITLE
Create Content sites for Storefront 1.0

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#66]
**Scope**  
Create new pages or move existing documentation from GitHub Wiki to the storefront in the 1.x Branch

**Subtasks**  
Add all related subtasks to be completed in order to finish the issue.
- [x] Create/Move pages as .md to Storefront 1.0
- [x] Check all contents within the Storefront 1.0 (Business)
- [x] Check all contents within the Storefront 1.0 (Dev)
- [x] Check all contents within the Storefront 1.0 (Design)
- [x] Push my commits to GitHub
