### ISSUE TITLE
Add prefixing callback/ Web Components Manager

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#679]
**Scope**
Add possibility to prefix design system components at runtime with custom defined prefix to scope project components.

**Out of scope**
- Integration into sample projects #725 
- Bundle size #855 

**Notes**
- There is an official discussion around scoping custom elements: https://github.com/w3c/webcomponents/issues/716

**Tasks**
- [x] Create code suggestion and fork for angular / react pre-fix modifications
- [x] Create PRs and issues for Angular / React Wrapper for Stencil
- [x] Fork Web Component Manager from My Porsche
- [x] ~~Support components like `flex` and `flex-item` without shadow dom~~
- [x] Use PWCM in storefront
- [x] Check Edge 18
- [x] `packages/components-js` should become __internal__ as `packages/components` and `packages/components-pwcm` should become `packages/components-js` 
- [x] Clean Angular Package
- [x] Clean React Package
- [x] Clean Storefront Package
- [x] Clean Mono Repo npm scripts
- [x] Clean Docker Scripts
- [x] Update CI/CD
- [x] Update npm dependencies
- [x] Check bundle size
- [x] ~~Check web component manager fork~~, new issue created
- [x] Align react project with js/angular
- [x] Refactor clean up tasks
- [x] Remove overview pages from VRT tests and add a page with all components in default config for JS/Angular/React
- [x] Add VRT test with component prefix in Angular
- [x] Add VRT test with component prefix in React
- [x] Final overall review
- [x] Release 2.0.0-alpha.0

**Notes**
* Tree Shaking icon and marque component not working properly
* Tree Shaking main bundle does not work properly (still contains utilities functions that are not needed)
* What about polyfills? Do we still need them because we won't support IE11 and EdgeHTML anymore. And if we need them, are we loading them twice with Stencil build and Web Component Manager build?
* Do we need JSON5 or can we write our own small Parser?

https://designsystem.porsche.com/issue/679/
