### ISSUE TITLE
Define Naming of Component Size Versions

### ISSUE THREAD

**Issue by annakrohmer** [porsche-design-system/porsche-design-system#68]
**Scope**  
We should define a general rule for naming different component sizes, differentiating between the following cases:

1. **For viewport-dependent sizes** = when a specific size is defined for each (or multiple) viewports → XS-XL (according to viewport namings) would make sense.
2. **For viewport-independent sizes** = when a component is simply available in multiple different sizes, e.g. small/medium/large, regardless of the viewport usage. → naming tbd. (Should not overlap with viewport-dependent namings!)

**Notes**  
- We should check if there are more size cases to be considered.
- For case 1, we should define how to handle the naming in Sketch, when a component size is valid for multiple viewports; e.g.: "component/XS-M/..." - or better duplicate the symbol and provide it for every single viewport ("component/XS/..." + "component/S/..." etc.)?
- Any differences between design and development?

**Subtasks**  
- [x] Create UI decision proposal based on research
- [x] Approve UI definition
- [x] Write down guideline in GitHub wiki
