### ISSUE TITLE
Add new font

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#683]
**Scope**
Add new font face with adjusted metrics to v2 code and design library / docu

**!!! The new font leads to breaking changes (new metrics) !!!**

**Notes**
- Check possibility to add font face to Sketch Library (https://www.sketch.com/updates/)

👉 Sktech 67.2
Embed Fonts in Documents: With this release, we’re introducing the option to embed font files in individual documents. You can do this in any document by choosing Text > Document Fonts… and selecting the fonts you want to embed. Embedding fonts makes it easier to share documents with others and ensures that text layers render accurately — even if they don’t have the right fonts installed. It also ensures text layers render correctly whenever you view your documents on Cloud.

Final font all styles and languages:
[2020.05.21_PorscheNext_v2.000_WOFF.zip](https://github.com/porscheui/porsche-design-system/files/4675810/2020.05.21_PorscheNext_v2.000_WOFF.zip)
[2020.05.21_PorscheNext_v2.000_OTF.zip](https://github.com/porscheui/porsche-design-system/files/4675812/2020.05.21_PorscheNext_v2.000_OTF.zip)

**Subtasks**
- [x] Add font assets to Sketch Basic & Web Libraries
- [x] Adjust components in web library regarding new metrics of the new font
- [x] Publish new font assets to packages
- [x] Integrate into sample projects
- [x] Release Basic and Web Library
