### ISSUE TITLE
Move NPM Package to Porsche UI Registry

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#7]
**Scope**  
AS Consumer
I WANT TO access the Porsche UI Kit NPM releases without VPN and P-/X-User
SO THAT I can access it more easily.

**Subtasks**  
Add all related subtasks to be completed in order to finish the issue.
- [x] Evaluate the possibility to duplicate / proxy the Porsche UI Kit NPM to the My Porsche and Porsche Highway environment (and delete artefacts afterwards in My Porsche npm registry)
- [x]  Move UI Kit React npm packages to self owned Artifactory
- [x]  Move visual regression tester to self owned Artifactory and self owned GitHub Repo
- [x]  Move the Porsche UI Kit NPMs to an self owned Artifactory
- [x]  Use @porsche for Porsche UI Kit 0.x and @porscheui for Porsche UI Kit 1.0
- [x]  Test deployment of current Porsche UI Kit Version
- [x]  Update docu in GitHub Repo / Wiki (also explain how to get access to registry and how to get started)
