### ISSUE TITLE
Scss convertLineHeight function rounding bug

### ISSUE THREAD

**Issue by anotherMatze** [porsche-design-system/porsche-design-system#710]
**Description**  
Our Scss convertLineHeight function rounds to the 5th decimal place.

**Expected behavior**  
Chrome etc. needs at least the 6th decimal place. The bug was discovered by using the js lineHeight function, in which we also round to the 5th decimal place, to get our vrt tests in sync.

**Tasks**
- [x] Refactor convertLineHeight in Scss and JS
- [x] Refactor helpers of Scss convertLineHeight
- [x] Rename utilities objects to plural -> See issue #735, finder wants singular naming
- [x] Use same import (dev/dependencies) of utilities package in angular and react -> will be handled in rc release branch!
