### ISSUE TITLE
Refine Components React Mocks

### ISSUE THREAD

**Issue by chrisalbert** [porsche-design-system/porsche-design-system#767]
**Scope**  
This task refines the mocks of react components in a number of ways for easier unit testing.

**Subtasks**
- [x] For form elements: add tests using both label and message at the same time
- [x] For form elements: wrap message and label props in html tags to enable easier testing with testing-library
- [x] For form elements: add description to form mocks
- [x] Add <i> tag to icon mock
- [x] Prevent children being spread implicitly and explicitly on the same component
