### ISSUE TITLE
Transfer Flex component from 0.x UI Kit React to 1.x UI Kit

### ISSUE THREAD

**Issue by o-hook** [porsche-design-system/porsche-design-system#78]
**Scope**  
Transfer Flex component and documrntation from 0.x UI Kit React to 1.x UI Kit

**Subtasks**  
- [x] Use spacing component directly in flex instead of creating new css classes
- [x] Transfer and adapt component code
- [x] Transfer and adapt component code documentation
- [x] Transfer and adapt component design documentation
- [x] Add new component to storefront
- [x] Rethink class namings of "justify-content" (--> "align-main-axis"), "align-items" (--> "align-cross-axis"), "align-self" (--> "cross-axis"). Do some Slack poll to get feedback of the teams?
- [x] Change above naming conventions to native flex namings
- [x] Add class/mixin/variable examples in form of code blocks or inline code blocks with description if necessary.
- [x] Add introduction text that those classes can be used for layouting with autoprefixed flex css styles but it's not obligatory to use this system (if someone creates a custom component of course custom flex css props can be used,… it's up to the dev)
- [x] Cross check with best flex documentation on earth: https://css-tricks.com/snippets/css/a-guide-to-flexbox/
- [x] Define & describe "default", what does it mean?
- [x] Remove redundant subtitles like "Wrap – something"
- [x] Think of using global css classes in Example TSX for styling component examples
- [x] Align items - start (default) => stretch is default! Please check all "default" states again.
- [x] Align content, stretch (default state) is missing
- [x] Add a short description for each Flex child shorthand example
- [x] Think of using FlexChild instead of FlexItem React component to be in sync with CSS classnames **=> No change here because official notation ist "flex item"**
- [x] Add VRT test
- [x] Think of creating a breakpoint class maker mixing and remove individual mixins in flex scss => basic major breakpoint mixin created, but works only for single/standalone values, not for groups, because they have to be wrapped inside the media query.
- [x] Change SFC to FC
