### ISSUE TITLE
Transfer Grid component from 0.x UI Kit React to 1.x UI Kit 

### ISSUE THREAD

**Issue by o-hook** [porsche-design-system/porsche-design-system#79]
**Scope**  
Transfer Grid component and documentation from 0.x UI Kit React to 1.x UI Kit

**Subtasks**  
- [x] Transfer and adapt component code
- [x] Transfer and adapt component code documentation
- [x] Transfer and adapt component design documentation / Add screens
- [x] Add new component to storefront
