### ISSUE TITLE
Create Style / Typography

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#8]
**Scope**  
Research and reevaluate the current UI definition of typography and finalize all typography related styles including headlines and body text.

**Notes**  
- We defined, matching headline and text styles/classes
- Create static and responsive (viewport) variables for text-sizes
- Create a responsive component for headlines (bold using text-size variables)
- Create a component for text using size variables (available as regular and thin)

**Preview**
https://ui.porsche.com/issue/8/#/general/home

**Subtasks**  
- [x] Find and decide on a scaling logic: https://porsche.slack.com/files/UFJ9DMXR6/FJH6Y4H8E/2019-05-03_porsche-ui-kit-typography-scaling.xlsx and 
[2019-05-09_porsche-ui-kit-typography-mapping.xlsx](https://github.com/porscheui/porsche-ui-kit/files/3165818/2019-05-09_porsche-ui-kit-typography-mapping.xlsx)
- [x] Create UI decision proposal based on research and testing
- [x] Definition of hierarchy structure and naming of all related states and variants in design and code
- [x] UI definition approved
- [x] Create/update Sketch library symbol 
- [x] Update and deploy Sketch basic library
- [x] Create UI/UX guidelines 
- [x] Create/update related styles (CSS) and component (JS)
- [x] Create samples of all possible states and variants
- [x] Refactor typography components (text, headline) as webcomponent
- [x] Create and perform VRT test
- [x] Test code visual and functional for optimized viewports (only one browser): 320px, 375px, 480px, 768px, 1024px, 1366px, 1920px
- [x] Test code visual and functional for all supported browsers in viewports: 320px, 480px, 760px, 1000px, 1300px, 1760px, 1920px
