### ISSUE TITLE
NGCC throws error with pds v1.5.0

### ISSUE THREAD

**Issue by anotherMatze** [porsche-design-system/porsche-design-system#801]
**Description**  

**To Reproduce**  
1. Go to sample project angular
2. Import porsche design system v1.5.0
3. execute 'yarn ngcc'

**Expected behavior**  
No Error

**Test Environment (please complete the following information):**  
Angular 9.1.11

**Error:**
Failed to compile entry-point @porsche-design-system/components-angular (main as umd) due to compilation errors:
node_modules/@porsche-design-system/components-angular/bundles/porsche-design-system-components-angular.umd.js:880:35 - error NG1010: Value at position 0 in the NgModule.declarations of PorscheDesignSystemModule is not a reference: [object Object]
880                     declarations: DECLARATIONS,

**Note**
The Bug appears due the upgrade of ng-packagr v9.1.5 -> 10.0.1

**Tasks:**
- [x] See if there is an solution to get it running with 10.0.1 or downgrade np-packagr
- [x] Extend README.md, to test `yarn ngcc` after dependency upgrade angular
- [x] Release with fixed Icons in patch release
