### ISSUE TITLE
Performance issues on Finder Dealer Page

### ISSUE THREAD

**Issue by o-hook** [porsche-design-system/porsche-design-system#874]
**Description**  
On the Porsche Finder Dealer Page there are massive performance issues in rendering. A lot of PDS components are used, mostly checkboxes and text components. Rendering time of components and statechange of checkboxes are superslow.

Question: Are a lot of components (>100) affecting the performance of the loading?

**To Reproduce**  
1. Go to https://finder-k.porsche.com/dealer/11556/de-DE/inventory
2. Hover on Multiselect
3. Check/Uncheck items
4. See poor rendering performance

**Expected behavior**  
A fast rendering performance on hover and click.
Also have a look on a Stencil performance Demo: https://stencil-performance-demo.netlify.app/

**Videos**  
- [inventory-list.mp4.zip](https://github.com/porscheui/porsche-design-system/files/5060936/inventory-list.mp4.zip)
- [performance.mp4.zip](https://github.com/porscheui/porsche-design-system/files/5073479/performance.mp4.zip)

---

**Test Environment (please complete the following information):**  
- PDS Version: 1.4.x
- Browser: Chrome/Firefox

---

Performance: 
<img width="1274" alt="Bildschirmfoto 2020-08-19 um 11 58 15" src="https://user-images.githubusercontent.com/60395476/90621287-ceccb680-e213-11ea-8d36-088ef6eac2ab.png">

**Tasks**
- [x] Simulate behavior in react sample project 
- [x] Check Finder project to find the root of the issue
- [x] Get finder confirmation
