### ISSUE TITLE
Create Image Component for Storefront

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#97]
**Subtasks**  
- [x] Develop integration of images inside *.mdx component documentation files while images are located nearby the component.
- [x] Limit asset copying to known formats, like `(jp?eg|png|gif)`
- [x] Add one working example
