### ISSUE TITLE
Prep / Rename Cover Artboard

### ISSUE THREAD

**Issue by oliviapala** [porsche-design-system/porsche-design-system#98]
*** Wird noch ausgefüllt ***

**Scope**  
Describe clearly the scope of the change. If possible use the format of a user story.

**Out of Scope**  
- List topics that are not part of this issue to be worked on.

**Notes**  
- Abstract Collection Link:
- Share any further information that is relevant for processing

**Props** (if relevant)  
- Name: e.g. Button Square
- States: e.g. default, hover, focus, active, disabled, loading
- Variants: e.g. filled, ghost
- Cases/Templates: e.g. row
- Themes: e.g. standard + inverted

**Subtasks**  
- [x] Create UI decision proposal based on research and testing
- [x] Definition of hierarchy structure and naming of all related states and variants in design and code
- [x] Approve UI definition
- [x] Create/update Sketch library symbol in Abstract and share collection link
- [x] Create UI/UX guidelines as .mdx
- [x] Create/update related code CSS / JS
- [x] Create samples of all possible states and variants
- [x] Create Code/Implementation guidelines as .mdx for corresponding component code
- [x] Create VRT
- [x] Create Unit test (Optional)
- [x] Test code visual and functional for optimized viewports (only one browser): 320px, 375px, 480px, 768px, 1024px, 1366px, 1920px
- [x] Test code visual and functional for all supported browsers in viewports: 320px, 480px, 760px, 1000px, 1300px, 1760px, 1920px
